// Code generated by go-swagger; DO NOT EDIT.

package repositories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetReposLookupRepoFullNameParams creates a new GetReposLookupRepoFullNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetReposLookupRepoFullNameParams() *GetReposLookupRepoFullNameParams {
	return &GetReposLookupRepoFullNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetReposLookupRepoFullNameParamsWithTimeout creates a new GetReposLookupRepoFullNameParams object
// with the ability to set a timeout on a request.
func NewGetReposLookupRepoFullNameParamsWithTimeout(timeout time.Duration) *GetReposLookupRepoFullNameParams {
	return &GetReposLookupRepoFullNameParams{
		timeout: timeout,
	}
}

// NewGetReposLookupRepoFullNameParamsWithContext creates a new GetReposLookupRepoFullNameParams object
// with the ability to set a context for a request.
func NewGetReposLookupRepoFullNameParamsWithContext(ctx context.Context) *GetReposLookupRepoFullNameParams {
	return &GetReposLookupRepoFullNameParams{
		Context: ctx,
	}
}

// NewGetReposLookupRepoFullNameParamsWithHTTPClient creates a new GetReposLookupRepoFullNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetReposLookupRepoFullNameParamsWithHTTPClient(client *http.Client) *GetReposLookupRepoFullNameParams {
	return &GetReposLookupRepoFullNameParams{
		HTTPClient: client,
	}
}

/*
GetReposLookupRepoFullNameParams contains all the parameters to send to the API endpoint

	for the get repos lookup repo full name operation.

	Typically these are written to a http.Request.
*/
type GetReposLookupRepoFullNameParams struct {

	/* Authorization.

	   Insert your personal access token

	   Default: "Bearer \u003cpersonal access token\u003e"
	*/
	Authorization string

	/* RepoFullName.

	   the repository full name / slug
	*/
	RepoFullName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get repos lookup repo full name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetReposLookupRepoFullNameParams) WithDefaults() *GetReposLookupRepoFullNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get repos lookup repo full name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetReposLookupRepoFullNameParams) SetDefaults() {
	var (
		authorizationDefault = string("Bearer <personal access token>")
	)

	val := GetReposLookupRepoFullNameParams{
		Authorization: authorizationDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get repos lookup repo full name params
func (o *GetReposLookupRepoFullNameParams) WithTimeout(timeout time.Duration) *GetReposLookupRepoFullNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get repos lookup repo full name params
func (o *GetReposLookupRepoFullNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get repos lookup repo full name params
func (o *GetReposLookupRepoFullNameParams) WithContext(ctx context.Context) *GetReposLookupRepoFullNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get repos lookup repo full name params
func (o *GetReposLookupRepoFullNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get repos lookup repo full name params
func (o *GetReposLookupRepoFullNameParams) WithHTTPClient(client *http.Client) *GetReposLookupRepoFullNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get repos lookup repo full name params
func (o *GetReposLookupRepoFullNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the get repos lookup repo full name params
func (o *GetReposLookupRepoFullNameParams) WithAuthorization(authorization string) *GetReposLookupRepoFullNameParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the get repos lookup repo full name params
func (o *GetReposLookupRepoFullNameParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithRepoFullName adds the repoFullName to the get repos lookup repo full name params
func (o *GetReposLookupRepoFullNameParams) WithRepoFullName(repoFullName string) *GetReposLookupRepoFullNameParams {
	o.SetRepoFullName(repoFullName)
	return o
}

// SetRepoFullName adds the repoFullName to the get repos lookup repo full name params
func (o *GetReposLookupRepoFullNameParams) SetRepoFullName(repoFullName string) {
	o.RepoFullName = repoFullName
}

// WriteToRequest writes these params to a swagger request
func (o *GetReposLookupRepoFullNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// path param repo_full_name
	if err := r.SetPathParam("repo_full_name", o.RepoFullName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
