// Code generated by go-swagger; DO NOT EDIT.

package repositories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPostReposRepoIDChownParams creates a new PostReposRepoIDChownParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostReposRepoIDChownParams() *PostReposRepoIDChownParams {
	return &PostReposRepoIDChownParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostReposRepoIDChownParamsWithTimeout creates a new PostReposRepoIDChownParams object
// with the ability to set a timeout on a request.
func NewPostReposRepoIDChownParamsWithTimeout(timeout time.Duration) *PostReposRepoIDChownParams {
	return &PostReposRepoIDChownParams{
		timeout: timeout,
	}
}

// NewPostReposRepoIDChownParamsWithContext creates a new PostReposRepoIDChownParams object
// with the ability to set a context for a request.
func NewPostReposRepoIDChownParamsWithContext(ctx context.Context) *PostReposRepoIDChownParams {
	return &PostReposRepoIDChownParams{
		Context: ctx,
	}
}

// NewPostReposRepoIDChownParamsWithHTTPClient creates a new PostReposRepoIDChownParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostReposRepoIDChownParamsWithHTTPClient(client *http.Client) *PostReposRepoIDChownParams {
	return &PostReposRepoIDChownParams{
		HTTPClient: client,
	}
}

/*
PostReposRepoIDChownParams contains all the parameters to send to the API endpoint

	for the post repos repo ID chown operation.

	Typically these are written to a http.Request.
*/
type PostReposRepoIDChownParams struct {

	/* Authorization.

	   Insert your personal access token

	   Default: "Bearer \u003cpersonal access token\u003e"
	*/
	Authorization string

	/* RepoID.

	   the repository id
	*/
	RepoID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post repos repo ID chown params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostReposRepoIDChownParams) WithDefaults() *PostReposRepoIDChownParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post repos repo ID chown params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostReposRepoIDChownParams) SetDefaults() {
	var (
		authorizationDefault = string("Bearer <personal access token>")
	)

	val := PostReposRepoIDChownParams{
		Authorization: authorizationDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the post repos repo ID chown params
func (o *PostReposRepoIDChownParams) WithTimeout(timeout time.Duration) *PostReposRepoIDChownParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post repos repo ID chown params
func (o *PostReposRepoIDChownParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post repos repo ID chown params
func (o *PostReposRepoIDChownParams) WithContext(ctx context.Context) *PostReposRepoIDChownParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post repos repo ID chown params
func (o *PostReposRepoIDChownParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post repos repo ID chown params
func (o *PostReposRepoIDChownParams) WithHTTPClient(client *http.Client) *PostReposRepoIDChownParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post repos repo ID chown params
func (o *PostReposRepoIDChownParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the post repos repo ID chown params
func (o *PostReposRepoIDChownParams) WithAuthorization(authorization string) *PostReposRepoIDChownParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the post repos repo ID chown params
func (o *PostReposRepoIDChownParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithRepoID adds the repoID to the post repos repo ID chown params
func (o *PostReposRepoIDChownParams) WithRepoID(repoID int64) *PostReposRepoIDChownParams {
	o.SetRepoID(repoID)
	return o
}

// SetRepoID adds the repoId to the post repos repo ID chown params
func (o *PostReposRepoIDChownParams) SetRepoID(repoID int64) {
	o.RepoID = repoID
}

// WriteToRequest writes these params to a swagger request
func (o *PostReposRepoIDChownParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// path param repo_id
	if err := r.SetPathParam("repo_id", swag.FormatInt64(o.RepoID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
