workspace:
  base: /go
  path: src/github.com/drone/envsubst

clone:
  git:
    image: woodpeckerci/plugin-git
    depth: 50

steps:
  build:
    image: golang:1.7
    commands:
      - go get -t ./...
      - go build
      - go test -v
