// Code generated by go-swagger; DO NOT EDIT.

package secrets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetSecretsParams creates a new GetSecretsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetSecretsParams() *GetSecretsParams {
	return &GetSecretsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetSecretsParamsWithTimeout creates a new GetSecretsParams object
// with the ability to set a timeout on a request.
func NewGetSecretsParamsWithTimeout(timeout time.Duration) *GetSecretsParams {
	return &GetSecretsParams{
		timeout: timeout,
	}
}

// NewGetSecretsParamsWithContext creates a new GetSecretsParams object
// with the ability to set a context for a request.
func NewGetSecretsParamsWithContext(ctx context.Context) *GetSecretsParams {
	return &GetSecretsParams{
		Context: ctx,
	}
}

// NewGetSecretsParamsWithHTTPClient creates a new GetSecretsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetSecretsParamsWithHTTPClient(client *http.Client) *GetSecretsParams {
	return &GetSecretsParams{
		HTTPClient: client,
	}
}

/*
GetSecretsParams contains all the parameters to send to the API endpoint

	for the get secrets operation.

	Typically these are written to a http.Request.
*/
type GetSecretsParams struct {

	/* Authorization.

	   Insert your personal access token

	   Default: "Bearer \u003cpersonal access token\u003e"
	*/
	Authorization string

	/* Page.

	   for response pagination, page offset number

	   Default: 1
	*/
	Page *int64

	/* PerPage.

	   for response pagination, max items per page

	   Default: 50
	*/
	PerPage *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get secrets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSecretsParams) WithDefaults() *GetSecretsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get secrets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSecretsParams) SetDefaults() {
	var (
		authorizationDefault = string("Bearer <personal access token>")

		pageDefault = int64(1)

		perPageDefault = int64(50)
	)

	val := GetSecretsParams{
		Authorization: authorizationDefault,
		Page:          &pageDefault,
		PerPage:       &perPageDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get secrets params
func (o *GetSecretsParams) WithTimeout(timeout time.Duration) *GetSecretsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get secrets params
func (o *GetSecretsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get secrets params
func (o *GetSecretsParams) WithContext(ctx context.Context) *GetSecretsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get secrets params
func (o *GetSecretsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get secrets params
func (o *GetSecretsParams) WithHTTPClient(client *http.Client) *GetSecretsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get secrets params
func (o *GetSecretsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the get secrets params
func (o *GetSecretsParams) WithAuthorization(authorization string) *GetSecretsParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the get secrets params
func (o *GetSecretsParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithPage adds the page to the get secrets params
func (o *GetSecretsParams) WithPage(page *int64) *GetSecretsParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get secrets params
func (o *GetSecretsParams) SetPage(page *int64) {
	o.Page = page
}

// WithPerPage adds the perPage to the get secrets params
func (o *GetSecretsParams) WithPerPage(perPage *int64) *GetSecretsParams {
	o.SetPerPage(perPage)
	return o
}

// SetPerPage adds the perPage to the get secrets params
func (o *GetSecretsParams) SetPerPage(perPage *int64) {
	o.PerPage = perPage
}

// WriteToRequest writes these params to a swagger request
func (o *GetSecretsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if o.Page != nil {

		// query param page
		var qrPage int64

		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt64(qrPage)
		if qPage != "" {

			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}
	}

	if o.PerPage != nil {

		// query param perPage
		var qrPerPage int64

		if o.PerPage != nil {
			qrPerPage = *o.PerPage
		}
		qPerPage := swag.FormatInt64(qrPerPage)
		if qPerPage != "" {

			if err := r.SetQueryParam("perPage", qPerPage); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
