workspace:
  base: /go
  path: src/github.com/drone/envsubst

steps:
  build:
    image: redis:3.0
    commands:
      - sleep 1 # redis needs a second to init
      - redis-cli -h redis1 ping
      - redis-cli -h redis2 ping
      - redis-cli -h redis1 set HELLO hello
      - redis-cli -h redis2 set HELLO hola
      - redis-cli -h redis1 get HELLO
      - redis-cli -h redis2 get HELLO

services:
  redis1:
    image: redis:3.0
  redis2:
    image: redis:3.0
