// Code generated by go-swagger; DO NOT EDIT.

package organization_permissions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"go.woodpecker-ci.org/woodpecker/v2/woodpecker-go/models"
)

// GetOrgsOrgIDPermissionsReader is a Reader for the GetOrgsOrgIDPermissions structure.
type GetOrgsOrgIDPermissionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOrgsOrgIDPermissionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetOrgsOrgIDPermissionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /orgs/{org_id}/permissions] GetOrgsOrgIDPermissions", response, response.Code())
	}
}

// NewGetOrgsOrgIDPermissionsOK creates a GetOrgsOrgIDPermissionsOK with default headers values
func NewGetOrgsOrgIDPermissionsOK() *GetOrgsOrgIDPermissionsOK {
	return &GetOrgsOrgIDPermissionsOK{}
}

/*
GetOrgsOrgIDPermissionsOK describes a response with status code 200, with default header values.

OK
*/
type GetOrgsOrgIDPermissionsOK struct {
	Payload []*models.OrgPerm
}

// IsSuccess returns true when this get orgs org Id permissions o k response has a 2xx status code
func (o *GetOrgsOrgIDPermissionsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get orgs org Id permissions o k response has a 3xx status code
func (o *GetOrgsOrgIDPermissionsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get orgs org Id permissions o k response has a 4xx status code
func (o *GetOrgsOrgIDPermissionsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get orgs org Id permissions o k response has a 5xx status code
func (o *GetOrgsOrgIDPermissionsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get orgs org Id permissions o k response a status code equal to that given
func (o *GetOrgsOrgIDPermissionsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get orgs org Id permissions o k response
func (o *GetOrgsOrgIDPermissionsOK) Code() int {
	return 200
}

func (o *GetOrgsOrgIDPermissionsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /orgs/{org_id}/permissions][%d] getOrgsOrgIdPermissionsOK %s", 200, payload)
}

func (o *GetOrgsOrgIDPermissionsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /orgs/{org_id}/permissions][%d] getOrgsOrgIdPermissionsOK %s", 200, payload)
}

func (o *GetOrgsOrgIDPermissionsOK) GetPayload() []*models.OrgPerm {
	return o.Payload
}

func (o *GetOrgsOrgIDPermissionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
