// Code generated by go-swagger; DO NOT EDIT.

package pipelines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteReposRepoIDPipelinesNumberReader is a Reader for the DeleteReposRepoIDPipelinesNumber structure.
type DeleteReposRepoIDPipelinesNumberReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteReposRepoIDPipelinesNumberReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteReposRepoIDPipelinesNumberNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /repos/{repo_id}/pipelines/{number}] DeleteReposRepoIDPipelinesNumber", response, response.Code())
	}
}

// NewDeleteReposRepoIDPipelinesNumberNoContent creates a DeleteReposRepoIDPipelinesNumberNoContent with default headers values
func NewDeleteReposRepoIDPipelinesNumberNoContent() *DeleteReposRepoIDPipelinesNumberNoContent {
	return &DeleteReposRepoIDPipelinesNumberNoContent{}
}

/*
DeleteReposRepoIDPipelinesNumberNoContent describes a response with status code 204, with default header values.

No Content
*/
type DeleteReposRepoIDPipelinesNumberNoContent struct {
}

// IsSuccess returns true when this delete repos repo Id pipelines number no content response has a 2xx status code
func (o *DeleteReposRepoIDPipelinesNumberNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete repos repo Id pipelines number no content response has a 3xx status code
func (o *DeleteReposRepoIDPipelinesNumberNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete repos repo Id pipelines number no content response has a 4xx status code
func (o *DeleteReposRepoIDPipelinesNumberNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete repos repo Id pipelines number no content response has a 5xx status code
func (o *DeleteReposRepoIDPipelinesNumberNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete repos repo Id pipelines number no content response a status code equal to that given
func (o *DeleteReposRepoIDPipelinesNumberNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the delete repos repo Id pipelines number no content response
func (o *DeleteReposRepoIDPipelinesNumberNoContent) Code() int {
	return 204
}

func (o *DeleteReposRepoIDPipelinesNumberNoContent) Error() string {
	return fmt.Sprintf("[DELETE /repos/{repo_id}/pipelines/{number}][%d] deleteReposRepoIdPipelinesNumberNoContent", 204)
}

func (o *DeleteReposRepoIDPipelinesNumberNoContent) String() string {
	return fmt.Sprintf("[DELETE /repos/{repo_id}/pipelines/{number}][%d] deleteReposRepoIdPipelinesNumberNoContent", 204)
}

func (o *DeleteReposRepoIDPipelinesNumberNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
