// Code generated by go-swagger; DO NOT EDIT.

package pipelines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPostReposRepoIDPipelinesNumberCancelParams creates a new PostReposRepoIDPipelinesNumberCancelParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostReposRepoIDPipelinesNumberCancelParams() *PostReposRepoIDPipelinesNumberCancelParams {
	return &PostReposRepoIDPipelinesNumberCancelParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostReposRepoIDPipelinesNumberCancelParamsWithTimeout creates a new PostReposRepoIDPipelinesNumberCancelParams object
// with the ability to set a timeout on a request.
func NewPostReposRepoIDPipelinesNumberCancelParamsWithTimeout(timeout time.Duration) *PostReposRepoIDPipelinesNumberCancelParams {
	return &PostReposRepoIDPipelinesNumberCancelParams{
		timeout: timeout,
	}
}

// NewPostReposRepoIDPipelinesNumberCancelParamsWithContext creates a new PostReposRepoIDPipelinesNumberCancelParams object
// with the ability to set a context for a request.
func NewPostReposRepoIDPipelinesNumberCancelParamsWithContext(ctx context.Context) *PostReposRepoIDPipelinesNumberCancelParams {
	return &PostReposRepoIDPipelinesNumberCancelParams{
		Context: ctx,
	}
}

// NewPostReposRepoIDPipelinesNumberCancelParamsWithHTTPClient creates a new PostReposRepoIDPipelinesNumberCancelParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostReposRepoIDPipelinesNumberCancelParamsWithHTTPClient(client *http.Client) *PostReposRepoIDPipelinesNumberCancelParams {
	return &PostReposRepoIDPipelinesNumberCancelParams{
		HTTPClient: client,
	}
}

/*
PostReposRepoIDPipelinesNumberCancelParams contains all the parameters to send to the API endpoint

	for the post repos repo ID pipelines number cancel operation.

	Typically these are written to a http.Request.
*/
type PostReposRepoIDPipelinesNumberCancelParams struct {

	/* Authorization.

	   Insert your personal access token

	   Default: "Bearer \u003cpersonal access token\u003e"
	*/
	Authorization string

	/* Number.

	   the number of the pipeline
	*/
	Number int64

	/* RepoID.

	   the repository id
	*/
	RepoID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post repos repo ID pipelines number cancel params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostReposRepoIDPipelinesNumberCancelParams) WithDefaults() *PostReposRepoIDPipelinesNumberCancelParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post repos repo ID pipelines number cancel params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostReposRepoIDPipelinesNumberCancelParams) SetDefaults() {
	var (
		authorizationDefault = string("Bearer <personal access token>")
	)

	val := PostReposRepoIDPipelinesNumberCancelParams{
		Authorization: authorizationDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the post repos repo ID pipelines number cancel params
func (o *PostReposRepoIDPipelinesNumberCancelParams) WithTimeout(timeout time.Duration) *PostReposRepoIDPipelinesNumberCancelParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post repos repo ID pipelines number cancel params
func (o *PostReposRepoIDPipelinesNumberCancelParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post repos repo ID pipelines number cancel params
func (o *PostReposRepoIDPipelinesNumberCancelParams) WithContext(ctx context.Context) *PostReposRepoIDPipelinesNumberCancelParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post repos repo ID pipelines number cancel params
func (o *PostReposRepoIDPipelinesNumberCancelParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post repos repo ID pipelines number cancel params
func (o *PostReposRepoIDPipelinesNumberCancelParams) WithHTTPClient(client *http.Client) *PostReposRepoIDPipelinesNumberCancelParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post repos repo ID pipelines number cancel params
func (o *PostReposRepoIDPipelinesNumberCancelParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the post repos repo ID pipelines number cancel params
func (o *PostReposRepoIDPipelinesNumberCancelParams) WithAuthorization(authorization string) *PostReposRepoIDPipelinesNumberCancelParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the post repos repo ID pipelines number cancel params
func (o *PostReposRepoIDPipelinesNumberCancelParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithNumber adds the number to the post repos repo ID pipelines number cancel params
func (o *PostReposRepoIDPipelinesNumberCancelParams) WithNumber(number int64) *PostReposRepoIDPipelinesNumberCancelParams {
	o.SetNumber(number)
	return o
}

// SetNumber adds the number to the post repos repo ID pipelines number cancel params
func (o *PostReposRepoIDPipelinesNumberCancelParams) SetNumber(number int64) {
	o.Number = number
}

// WithRepoID adds the repoID to the post repos repo ID pipelines number cancel params
func (o *PostReposRepoIDPipelinesNumberCancelParams) WithRepoID(repoID int64) *PostReposRepoIDPipelinesNumberCancelParams {
	o.SetRepoID(repoID)
	return o
}

// SetRepoID adds the repoId to the post repos repo ID pipelines number cancel params
func (o *PostReposRepoIDPipelinesNumberCancelParams) SetRepoID(repoID int64) {
	o.RepoID = repoID
}

// WriteToRequest writes these params to a swagger request
func (o *PostReposRepoIDPipelinesNumberCancelParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// path param number
	if err := r.SetPathParam("number", swag.FormatInt64(o.Number)); err != nil {
		return err
	}

	// path param repo_id
	if err := r.SetPathParam("repo_id", swag.FormatInt64(o.RepoID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
