// Code generated by go-swagger; DO NOT EDIT.

package pipelines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"go.woodpecker-ci.org/woodpecker/v2/woodpecker-go/models"
)

// PostReposRepoIDPipelinesNumberReader is a Reader for the PostReposRepoIDPipelinesNumber structure.
type PostReposRepoIDPipelinesNumberReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostReposRepoIDPipelinesNumberReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostReposRepoIDPipelinesNumberOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /repos/{repo_id}/pipelines/{number}] PostReposRepoIDPipelinesNumber", response, response.Code())
	}
}

// NewPostReposRepoIDPipelinesNumberOK creates a PostReposRepoIDPipelinesNumberOK with default headers values
func NewPostReposRepoIDPipelinesNumberOK() *PostReposRepoIDPipelinesNumberOK {
	return &PostReposRepoIDPipelinesNumberOK{}
}

/*
PostReposRepoIDPipelinesNumberOK describes a response with status code 200, with default header values.

OK
*/
type PostReposRepoIDPipelinesNumberOK struct {
	Payload *models.Pipeline
}

// IsSuccess returns true when this post repos repo Id pipelines number o k response has a 2xx status code
func (o *PostReposRepoIDPipelinesNumberOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post repos repo Id pipelines number o k response has a 3xx status code
func (o *PostReposRepoIDPipelinesNumberOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post repos repo Id pipelines number o k response has a 4xx status code
func (o *PostReposRepoIDPipelinesNumberOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post repos repo Id pipelines number o k response has a 5xx status code
func (o *PostReposRepoIDPipelinesNumberOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post repos repo Id pipelines number o k response a status code equal to that given
func (o *PostReposRepoIDPipelinesNumberOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post repos repo Id pipelines number o k response
func (o *PostReposRepoIDPipelinesNumberOK) Code() int {
	return 200
}

func (o *PostReposRepoIDPipelinesNumberOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /repos/{repo_id}/pipelines/{number}][%d] postReposRepoIdPipelinesNumberOK %s", 200, payload)
}

func (o *PostReposRepoIDPipelinesNumberOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /repos/{repo_id}/pipelines/{number}][%d] postReposRepoIdPipelinesNumberOK %s", 200, payload)
}

func (o *PostReposRepoIDPipelinesNumberOK) GetPayload() *models.Pipeline {
	return o.Payload
}

func (o *PostReposRepoIDPipelinesNumberOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Pipeline)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
