changelog:
  skip: true
nfpms:
  - id: server
    package_name: server
    builds:
      - server
    file_name_template: "{{ .ProjectName }}-{{ .PackageName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    homepage: https://github.com/woodpecker-ci/woodpecker
    license: Apache 2.0
    formats:
      - apk
      - deb
      - rpm
    meta: true
  - id: agent
    package_name: agent
    builds:
      - agent
    file_name_template: "{{ .ProjectName }}-{{ .PackageName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    homepage: https://github.com/woodpecker-ci/woodpecker
    license: Apache 2.0
    formats:
      - apk
      - deb
      - rpm
    meta: true
  - id: cli
    package_name: cli
    builds:
      - cli
    file_name_template: "{{ .ProjectName }}-{{ .PackageName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    homepage: https://github.com/woodpecker-ci/woodpecker
    license: Apache 2.0
    formats:
      - apk
      - deb
      - rpm
    meta: true
