---
all: true
dir: '{{.InterfaceDir}}/mocks'
filename: mock_{{.InterfaceName}}.go
pkgname: mocks
recursive: true
packages:
  go.woodpecker-ci.org/woodpecker/v3/pipeline/rpc:
  go.woodpecker-ci.org/woodpecker/v3/server/forge:
  go.woodpecker-ci.org/woodpecker/v3/server/queue:
  go.woodpecker-ci.org/woodpecker/v3/server/services:
  go.woodpecker-ci.org/woodpecker/v3/server/services/config:
  go.woodpecker-ci.org/woodpecker/v3/server/services/environment:
  go.woodpecker-ci.org/woodpecker/v3/server/services/registry:
  go.woodpecker-ci.org/woodpecker/v3/server/services/secret:
  go.woodpecker-ci.org/woodpecker/v3/server/store:
  go.woodpecker-ci.org/woodpecker/v3/woodpecker-go/woodpecker:
