# docker build --rm -f Dockerfile.agent -t woodpeckerci/woodpecker-agent .

FROM drone/ca-certs
ENV GODEBUG=netdns=go
ADD release/woodpecker-agent /bin/

EXPOSE 3000
HEALTHCHECK CMD ["/bin/woodpecker-agent", "ping"]

ENTRYPOINT ["/bin/woodpecker-agent"]
