// Copyright 2024 Woodpecker Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package common

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

const (
	// UTF-16LE encoded script, base64 encoded for powershell's -encodedcommand.
	windowsScriptBase64 = "CgAkAEwAQQBTAFQARQBYAEkAVABDAE8ARABFACAAPQAgADAACgAkAEUAcgByAG8AcgBBAGMAdABpAG8AbgBQAHIAZQBmAGUAcgBlAG4AYwBlACAAPQAgACcAUwB0AG8AcAAnADsACgBpAGYAIAAoAC0AbgBvAHQAIAAoAFQAZQBzAHQALQBQAGEAdABoACAAIgAvAHcAbwBvAGQAcABlAGMAawBlAHIALwBzAG8AbQBlACIAKQApACAAewAgAE4AZQB3AC0ASQB0AGUAbQAgAC0AUABhAHQAaAAgACIALwB3AG8AbwBkAHAAZQBjAGsAZQByAC8AcwBvAG0AZQAiACAALQBJAHQAZQBtAFQAeQBwAGUAIABEAGkAcgBlAGMAdABvAHIAeQAgAC0ARgBvAHIAYwBlACAAfQA7AAoAaQBmACAAKAAtAG4AbwB0ACAAWwBFAG4AdgBpAHIAbwBuAG0AZQBuAHQAXQA6ADoARwBlAHQARQBuAHYAaQByAG8AbgBtAGUAbgB0AFYAYQByAGkAYQBiAGwAZQAoACcASABPAE0ARQAnACkAKQAgAHsAIABbAEUAbgB2AGkAcgBvAG4AbQBlAG4AdABdADoAOgBTAGUAdABFAG4AdgBpAHIAbwBuAG0AZQBuAHQAVgBhAHIAaQBhAGIAbABlACgAJwBIAE8ATQBFACcALAAgACcAYwA6AFwAcgBvAG8AdAAnACkAIAB9ADsACgBpAGYAIAAoAC0AbgBvAHQAIAAoAFQAZQBzAHQALQBQAGEAdABoACAAIgAkAGUAbgB2ADoASABPAE0ARQAiACkAKQAgAHsAIABOAGUAdwAtAEkAdABlAG0AIAAtAFAAYQB0AGgAIAAiACQAZQBuAHYAOgBIAE8ATQBFACIAIAAtAEkAdABlAG0AVAB5AHAAZQAgAEQAaQByAGUAYwB0AG8AcgB5ACAALQBGAG8AcgBjAGUAIAB9ADsACgBpAGYAIAAoACQARQBuAHYAOgBDAEkAXwBOAEUAVABSAEMAXwBNAEEAQwBIAEkATgBFACkAIAB7AAoAJABuAGUAdAByAGMAPQBbAHMAdAByAGkAbgBnAF0AOgA6AEYAbwByAG0AYQB0ACgAIgB7ADAAfQBcAF8AbgBlAHQAcgBjACIALAAkAEUAbgB2ADoASABPAE0ARQApADsACgAiAG0AYQBjAGgAaQBuAGUAIAAkAEUAbgB2ADoAQwBJAF8ATgBFAFQAUgBDAF8ATQBBAEMASABJAE4ARQAiACAAPgA+ACAAJABuAGUAdAByAGMAOwAKACIAbABvAGcAaQBuACAAJABFAG4AdgA6AEMASQBfAE4ARQBUAFIAQwBfAFUAUwBFAFIATgBBAE0ARQAiACAAPgA+ACAAJABuAGUAdAByAGMAOwAKACIAcABhAHMAcwB3AG8AcgBkACAAJABFAG4AdgA6AEMASQBfAE4ARQBUAFIAQwBfAFAAQQBTAFMAVwBPAFIARAAiACAAPgA+ACAAJABuAGUAdAByAGMAOwAKAH0AOwAKAFsARQBuAHYAaQByAG8AbgBtAGUAbgB0AF0AOgA6AFMAZQB0AEUAbgB2AGkAcgBvAG4AbQBlAG4AdABWAGEAcgBpAGEAYgBsAGUAKAAiAEMASQBfAE4ARQBUAFIAQwBfAFAAQQBTAFMAVwBPAFIARAAiACwAJABuAHUAbABsACkAOwAKAFsARQBuAHYAaQByAG8AbgBtAGUAbgB0AF0AOgA6AFMAZQB0AEUAbgB2AGkAcgBvAG4AbQBlAG4AdABWAGEAcgBpAGEAYgBsAGUAKAAiAEMASQBfAFMAQwBSAEkAUABUACIALAAkAG4AdQBsAGwAKQA7AAoAYwBkACAAIgAvAHcAbwBvAGQAcABlAGMAawBlAHIALwBzAG8AbQBlACIAOwAKAAoAVwByAGkAdABlAC0ATwB1AHQAcAB1AHQAIAAoACcAKwAgACIAZQBjAGgAbwAgAGgAZQBsAGwAbwAgAHcAbwByAGwAZAAiACcAKQA7AAoAJgAgAGUAYwBoAG8AIABoAGUAbABsAG8AIAB3AG8AcgBsAGQAOwAgAGkAZgAgACgAJABMAEEAUwBUAEUAWABJAFQAQwBPAEQARQAgAC0AbgBlACAAMAApACAAewBlAHgAaQB0ACAAJABMAEEAUwBUAEUAWABJAFQAQwBPAEQARQB9AAoA"
	posixScriptBase64   = "CmlmIFsgLW4gIiRDSV9ORVRSQ19NQUNISU5FIiBdOyB0aGVuCmNhdCA8PEVPRiA+ICRIT01FLy5uZXRyYwptYWNoaW5lICRDSV9ORVRSQ19NQUNISU5FCmxvZ2luICRDSV9ORVRSQ19VU0VSTkFNRQpwYXNzd29yZCAkQ0lfTkVUUkNfUEFTU1dPUkQKRU9GCmNobW9kIDA2MDAgJEhPTUUvLm5ldHJjCmZpCnVuc2V0IENJX05FVFJDX1VTRVJOQU1FCnVuc2V0IENJX05FVFJDX1BBU1NXT1JECnVuc2V0IENJX1NDUklQVApta2RpciAtcCAiL3dvb2RwZWNrZXIvc29tZSIKY2QgIi93b29kcGVja2VyL3NvbWUiCgplY2hvICsgJ2VjaG8gaGVsbG8gd29ybGQnCmVjaG8gaGVsbG8gd29ybGQK"
)

func TestGenerateContainerConf(t *testing.T) {
	gotEnv, gotEntry, err := GenerateContainerConf([]string{"echo hello world"}, "windows", "/woodpecker/some")
	require.NoError(t, err)
	assert.Equal(t, windowsScriptBase64, gotEnv["CI_SCRIPT"])
	assert.Equal(t, "powershell.exe", gotEnv["SHELL"])
	assert.Equal(t, []string{"powershell", "-noprofile", "-noninteractive", "-encodedcommand", windowsScriptBase64}, gotEntry)
	gotEnv, gotEntry, err = GenerateContainerConf([]string{"echo hello world"}, "linux", "/woodpecker/some")
	require.NoError(t, err)
	assert.Equal(t, posixScriptBase64, gotEnv["CI_SCRIPT"])
	assert.Equal(t, "/bin/sh", gotEnv["SHELL"])
	assert.Equal(t, []string{"/bin/sh", "-c", "echo $CI_SCRIPT | base64 -d | /bin/sh -e"}, gotEntry)
}
