// Code generated by go generate; DO NOT EDIT.

package migration

import (
	"context"

	"xorm.io/xorm"

	"go.woodpecker-ci.org/woodpecker/v2/server/model"
)

func CopyData(ctx context.Context, src, dest *xorm.Engine) error {
	if err := copyBean[model.Agent](ctx, src, dest); err != nil {
		return err
	}
	if err := copyBean[model.Pipeline](ctx, src, dest); err != nil {
		return err
	}
	if err := copyBean[model.PipelineConfig](ctx, src, dest); err != nil {
		return err
	}
	if err := copyBean[model.Config](ctx, src, dest); err != nil {
		return err
	}
	if err := copyBean[model.LogEntry](ctx, src, dest); err != nil {
		return err
	}
	if err := copyBean[model.Perm](ctx, src, dest); err != nil {
		return err
	}
	if err := copyBean[model.Step](ctx, src, dest); err != nil {
		return err
	}
	if err := copyBean[model.Registry](ctx, src, dest); err != nil {
		return err
	}
	if err := copyBean[model.Repo](ctx, src, dest); err != nil {
		return err
	}
	if err := copyBean[model.Secret](ctx, src, dest); err != nil {
		return err
	}
	if err := copyBean[model.Task](ctx, src, dest); err != nil {
		return err
	}
	if err := copyBean[model.User](ctx, src, dest); err != nil {
		return err
	}
	if err := copyBean[model.ServerConfig](ctx, src, dest); err != nil {
		return err
	}
	if err := copyBean[model.Cron](ctx, src, dest); err != nil {
		return err
	}
	if err := copyBean[model.Redirection](ctx, src, dest); err != nil {
		return err
	}
	if err := copyBean[model.Forge](ctx, src, dest); err != nil {
		return err
	}
	if err := copyBean[model.Workflow](ctx, src, dest); err != nil {
		return err
	}
	if err := copyBean[model.Org](ctx, src, dest); err != nil {
		return err
	}
	return nil
}
