// Code generated by go-swagger; DO NOT EDIT.

package pipeline_logs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteReposRepoIDLogsNumberReader is a Reader for the DeleteReposRepoIDLogsNumber structure.
type DeleteReposRepoIDLogsNumberReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteReposRepoIDLogsNumberReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteReposRepoIDLogsNumberNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /repos/{repo_id}/logs/{number}] DeleteReposRepoIDLogsNumber", response, response.Code())
	}
}

// NewDeleteReposRepoIDLogsNumberNoContent creates a DeleteReposRepoIDLogsNumberNoContent with default headers values
func NewDeleteReposRepoIDLogsNumberNoContent() *DeleteReposRepoIDLogsNumberNoContent {
	return &DeleteReposRepoIDLogsNumberNoContent{}
}

/*
DeleteReposRepoIDLogsNumberNoContent describes a response with status code 204, with default header values.

No Content
*/
type DeleteReposRepoIDLogsNumberNoContent struct {
}

// IsSuccess returns true when this delete repos repo Id logs number no content response has a 2xx status code
func (o *DeleteReposRepoIDLogsNumberNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete repos repo Id logs number no content response has a 3xx status code
func (o *DeleteReposRepoIDLogsNumberNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete repos repo Id logs number no content response has a 4xx status code
func (o *DeleteReposRepoIDLogsNumberNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete repos repo Id logs number no content response has a 5xx status code
func (o *DeleteReposRepoIDLogsNumberNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete repos repo Id logs number no content response a status code equal to that given
func (o *DeleteReposRepoIDLogsNumberNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the delete repos repo Id logs number no content response
func (o *DeleteReposRepoIDLogsNumberNoContent) Code() int {
	return 204
}

func (o *DeleteReposRepoIDLogsNumberNoContent) Error() string {
	return fmt.Sprintf("[DELETE /repos/{repo_id}/logs/{number}][%d] deleteReposRepoIdLogsNumberNoContent", 204)
}

func (o *DeleteReposRepoIDLogsNumberNoContent) String() string {
	return fmt.Sprintf("[DELETE /repos/{repo_id}/logs/{number}][%d] deleteReposRepoIdLogsNumberNoContent", 204)
}

func (o *DeleteReposRepoIDLogsNumberNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
