// Code generated by go-swagger; DO NOT EDIT.

package pipeline_logs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"go.woodpecker-ci.org/woodpecker/v2/woodpecker-go/models"
)

// GetReposRepoIDLogsNumberStepIDReader is a Reader for the GetReposRepoIDLogsNumberStepID structure.
type GetReposRepoIDLogsNumberStepIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetReposRepoIDLogsNumberStepIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetReposRepoIDLogsNumberStepIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /repos/{repo_id}/logs/{number}/{stepID}] GetReposRepoIDLogsNumberStepID", response, response.Code())
	}
}

// NewGetReposRepoIDLogsNumberStepIDOK creates a GetReposRepoIDLogsNumberStepIDOK with default headers values
func NewGetReposRepoIDLogsNumberStepIDOK() *GetReposRepoIDLogsNumberStepIDOK {
	return &GetReposRepoIDLogsNumberStepIDOK{}
}

/*
GetReposRepoIDLogsNumberStepIDOK describes a response with status code 200, with default header values.

OK
*/
type GetReposRepoIDLogsNumberStepIDOK struct {
	Payload []*models.LogEntry
}

// IsSuccess returns true when this get repos repo Id logs number step Id o k response has a 2xx status code
func (o *GetReposRepoIDLogsNumberStepIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get repos repo Id logs number step Id o k response has a 3xx status code
func (o *GetReposRepoIDLogsNumberStepIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get repos repo Id logs number step Id o k response has a 4xx status code
func (o *GetReposRepoIDLogsNumberStepIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get repos repo Id logs number step Id o k response has a 5xx status code
func (o *GetReposRepoIDLogsNumberStepIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get repos repo Id logs number step Id o k response a status code equal to that given
func (o *GetReposRepoIDLogsNumberStepIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get repos repo Id logs number step Id o k response
func (o *GetReposRepoIDLogsNumberStepIDOK) Code() int {
	return 200
}

func (o *GetReposRepoIDLogsNumberStepIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /repos/{repo_id}/logs/{number}/{stepID}][%d] getReposRepoIdLogsNumberStepIdOK %s", 200, payload)
}

func (o *GetReposRepoIDLogsNumberStepIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /repos/{repo_id}/logs/{number}/{stepID}][%d] getReposRepoIdLogsNumberStepIdOK %s", 200, payload)
}

func (o *GetReposRepoIDLogsNumberStepIDOK) GetPayload() []*models.LogEntry {
	return o.Payload
}

func (o *GetReposRepoIDLogsNumberStepIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
