workspace:
  base: /go
  path: src/github.com/woodpecker-ci/woodpecker/cncd/pipeline

pipeline:
  install:
    image: golang:1.8
    commands:
      - go install github.com/woodpecker-ci/woodpecker/cncd/pipeline/pipec
      - go install github.com/woodpecker-ci/woodpecker/cncd/pipeline/piped

  test:
    image: golang:1.8
    commands:
      - go test -cover -timeout 30s github.com/woodpecker-ci/woodpecker/cncd/pipeline/...
