workspace:
  base: /go
  path: src/github.com/drone/envsubst

clone:
  git:
    image: plugins/git
    depth: 50

pipeline:
  build:
    image: golang:1.7
    commands:
      - go get -t ./...
      - go build
      - go test -v

  slack:
    image: plugins/slack
    channel: builds
    username: drone
    secrets: [ slack_webhook ]
