// Code generated by go-swagger; DO NOT EDIT.

package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetHealthzReader is a Reader for the GetHealthz structure.
type GetHealthzReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetHealthzReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewGetHealthzNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetHealthzInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /healthz] GetHealthz", response, response.Code())
	}
}

// NewGetHealthzNoContent creates a GetHealthzNoContent with default headers values
func NewGetHealthzNoContent() *GetHealthzNoContent {
	return &GetHealthzNoContent{}
}

/*
GetHealthzNoContent describes a response with status code 204, with default header values.

No Content
*/
type GetHealthzNoContent struct {
}

// IsSuccess returns true when this get healthz no content response has a 2xx status code
func (o *GetHealthzNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get healthz no content response has a 3xx status code
func (o *GetHealthzNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get healthz no content response has a 4xx status code
func (o *GetHealthzNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this get healthz no content response has a 5xx status code
func (o *GetHealthzNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this get healthz no content response a status code equal to that given
func (o *GetHealthzNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the get healthz no content response
func (o *GetHealthzNoContent) Code() int {
	return 204
}

func (o *GetHealthzNoContent) Error() string {
	return fmt.Sprintf("[GET /healthz][%d] getHealthzNoContent", 204)
}

func (o *GetHealthzNoContent) String() string {
	return fmt.Sprintf("[GET /healthz][%d] getHealthzNoContent", 204)
}

func (o *GetHealthzNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetHealthzInternalServerError creates a GetHealthzInternalServerError with default headers values
func NewGetHealthzInternalServerError() *GetHealthzInternalServerError {
	return &GetHealthzInternalServerError{}
}

/*
GetHealthzInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetHealthzInternalServerError struct {
}

// IsSuccess returns true when this get healthz internal server error response has a 2xx status code
func (o *GetHealthzInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get healthz internal server error response has a 3xx status code
func (o *GetHealthzInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get healthz internal server error response has a 4xx status code
func (o *GetHealthzInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get healthz internal server error response has a 5xx status code
func (o *GetHealthzInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get healthz internal server error response a status code equal to that given
func (o *GetHealthzInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get healthz internal server error response
func (o *GetHealthzInternalServerError) Code() int {
	return 500
}

func (o *GetHealthzInternalServerError) Error() string {
	return fmt.Sprintf("[GET /healthz][%d] getHealthzInternalServerError", 500)
}

func (o *GetHealthzInternalServerError) String() string {
	return fmt.Sprintf("[GET /healthz][%d] getHealthzInternalServerError", 500)
}

func (o *GetHealthzInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
