// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockSetupIntentValue creates a new instance of MockSetupIntentValue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSetupIntentValue(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSetupIntentValue {
	mock := &MockSetupIntentValue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSetupIntentValue is an autogenerated mock type for the SetupIntentValue type
type MockSetupIntentValue struct {
	mock.Mock
}

type MockSetupIntentValue_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSetupIntentValue) EXPECT() *MockSetupIntentValue_Expecter {
	return &MockSetupIntentValue_Expecter{mock: &_m.Mock}
}

// isSetupIntent provides a mock function for the type MockSetupIntentValue
func (_mock *MockSetupIntentValue) isSetupIntent() {
	_mock.Called()
	return
}

// MockSetupIntentValue_isSetupIntent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'isSetupIntent'
type MockSetupIntentValue_isSetupIntent_Call struct {
	*mock.Call
}

// isSetupIntent is a helper method to define mock.On call
func (_e *MockSetupIntentValue_Expecter) isSetupIntent() *MockSetupIntentValue_isSetupIntent_Call {
	return &MockSetupIntentValue_isSetupIntent_Call{Call: _e.mock.On("isSetupIntent")}
}

func (_c *MockSetupIntentValue_isSetupIntent_Call) Run(run func()) *MockSetupIntentValue_isSetupIntent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSetupIntentValue_isSetupIntent_Call) Return() *MockSetupIntentValue_isSetupIntent_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSetupIntentValue_isSetupIntent_Call) RunAndReturn(run func()) *MockSetupIntentValue_isSetupIntent_Call {
	_c.Run(run)
	return _c
}
