workspace:
  base: /go
  path: src/github.com/drone/envsubst

clone:
  git:
    image: plugins/git
    depth: 50

pipeline:
  build:
    image: golang:1.7
    commands:
      - echo this step should fail
      - exit 1
  test:
    image: golang:1.7
    commands:
      - echo this step should never execute
