platform: windows/amd64

workspace:
  base: c:\gopath
  path: src\github.com\drone\envsubst

clone:
  git:
    image: woodpeckerci/plugin-git:windows
    depth: 50

steps:
  build:
    image: golang:1.10.1-nanoserver-sac2016
    commands:
      - go get -t .\...
      - go build
      - go test -v
