// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteUserTokenParams creates a new DeleteUserTokenParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteUserTokenParams() *DeleteUserTokenParams {
	return &DeleteUserTokenParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteUserTokenParamsWithTimeout creates a new DeleteUserTokenParams object
// with the ability to set a timeout on a request.
func NewDeleteUserTokenParamsWithTimeout(timeout time.Duration) *DeleteUserTokenParams {
	return &DeleteUserTokenParams{
		timeout: timeout,
	}
}

// NewDeleteUserTokenParamsWithContext creates a new DeleteUserTokenParams object
// with the ability to set a context for a request.
func NewDeleteUserTokenParamsWithContext(ctx context.Context) *DeleteUserTokenParams {
	return &DeleteUserTokenParams{
		Context: ctx,
	}
}

// NewDeleteUserTokenParamsWithHTTPClient creates a new DeleteUserTokenParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteUserTokenParamsWithHTTPClient(client *http.Client) *DeleteUserTokenParams {
	return &DeleteUserTokenParams{
		HTTPClient: client,
	}
}

/*
DeleteUserTokenParams contains all the parameters to send to the API endpoint

	for the delete user token operation.

	Typically these are written to a http.Request.
*/
type DeleteUserTokenParams struct {

	/* Authorization.

	   Insert your personal access token

	   Default: "Bearer \u003cpersonal access token\u003e"
	*/
	Authorization string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete user token params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteUserTokenParams) WithDefaults() *DeleteUserTokenParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete user token params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteUserTokenParams) SetDefaults() {
	var (
		authorizationDefault = string("Bearer <personal access token>")
	)

	val := DeleteUserTokenParams{
		Authorization: authorizationDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the delete user token params
func (o *DeleteUserTokenParams) WithTimeout(timeout time.Duration) *DeleteUserTokenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete user token params
func (o *DeleteUserTokenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete user token params
func (o *DeleteUserTokenParams) WithContext(ctx context.Context) *DeleteUserTokenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete user token params
func (o *DeleteUserTokenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete user token params
func (o *DeleteUserTokenParams) WithHTTPClient(client *http.Client) *DeleteUserTokenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete user token params
func (o *DeleteUserTokenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the delete user token params
func (o *DeleteUserTokenParams) WithAuthorization(authorization string) *DeleteUserTokenParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the delete user token params
func (o *DeleteUserTokenParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteUserTokenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
