// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetUserFeedParams creates a new GetUserFeedParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetUserFeedParams() *GetUserFeedParams {
	return &GetUserFeedParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetUserFeedParamsWithTimeout creates a new GetUserFeedParams object
// with the ability to set a timeout on a request.
func NewGetUserFeedParamsWithTimeout(timeout time.Duration) *GetUserFeedParams {
	return &GetUserFeedParams{
		timeout: timeout,
	}
}

// NewGetUserFeedParamsWithContext creates a new GetUserFeedParams object
// with the ability to set a context for a request.
func NewGetUserFeedParamsWithContext(ctx context.Context) *GetUserFeedParams {
	return &GetUserFeedParams{
		Context: ctx,
	}
}

// NewGetUserFeedParamsWithHTTPClient creates a new GetUserFeedParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetUserFeedParamsWithHTTPClient(client *http.Client) *GetUserFeedParams {
	return &GetUserFeedParams{
		HTTPClient: client,
	}
}

/*
GetUserFeedParams contains all the parameters to send to the API endpoint

	for the get user feed operation.

	Typically these are written to a http.Request.
*/
type GetUserFeedParams struct {

	/* Authorization.

	   Insert your personal access token

	   Default: "Bearer \u003cpersonal access token\u003e"
	*/
	Authorization string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get user feed params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUserFeedParams) WithDefaults() *GetUserFeedParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get user feed params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUserFeedParams) SetDefaults() {
	var (
		authorizationDefault = string("Bearer <personal access token>")
	)

	val := GetUserFeedParams{
		Authorization: authorizationDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get user feed params
func (o *GetUserFeedParams) WithTimeout(timeout time.Duration) *GetUserFeedParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get user feed params
func (o *GetUserFeedParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get user feed params
func (o *GetUserFeedParams) WithContext(ctx context.Context) *GetUserFeedParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get user feed params
func (o *GetUserFeedParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get user feed params
func (o *GetUserFeedParams) WithHTTPClient(client *http.Client) *GetUserFeedParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get user feed params
func (o *GetUserFeedParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the get user feed params
func (o *GetUserFeedParams) WithAuthorization(authorization string) *GetUserFeedParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the get user feed params
func (o *GetUserFeedParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WriteToRequest writes these params to a swagger request
func (o *GetUserFeedParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
