// Code generated by go-swagger; DO NOT EDIT.

package repository_cron_jobs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"go.woodpecker-ci.org/woodpecker/v2/woodpecker-go/models"
)

// NewPostReposRepoIDCronParams creates a new PostReposRepoIDCronParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostReposRepoIDCronParams() *PostReposRepoIDCronParams {
	return &PostReposRepoIDCronParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostReposRepoIDCronParamsWithTimeout creates a new PostReposRepoIDCronParams object
// with the ability to set a timeout on a request.
func NewPostReposRepoIDCronParamsWithTimeout(timeout time.Duration) *PostReposRepoIDCronParams {
	return &PostReposRepoIDCronParams{
		timeout: timeout,
	}
}

// NewPostReposRepoIDCronParamsWithContext creates a new PostReposRepoIDCronParams object
// with the ability to set a context for a request.
func NewPostReposRepoIDCronParamsWithContext(ctx context.Context) *PostReposRepoIDCronParams {
	return &PostReposRepoIDCronParams{
		Context: ctx,
	}
}

// NewPostReposRepoIDCronParamsWithHTTPClient creates a new PostReposRepoIDCronParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostReposRepoIDCronParamsWithHTTPClient(client *http.Client) *PostReposRepoIDCronParams {
	return &PostReposRepoIDCronParams{
		HTTPClient: client,
	}
}

/*
PostReposRepoIDCronParams contains all the parameters to send to the API endpoint

	for the post repos repo ID cron operation.

	Typically these are written to a http.Request.
*/
type PostReposRepoIDCronParams struct {

	/* Authorization.

	   Insert your personal access token

	   Default: "Bearer \u003cpersonal access token\u003e"
	*/
	Authorization string

	/* CronJob.

	   the new cron job
	*/
	CronJob *models.Cron

	/* RepoID.

	   the repository id
	*/
	RepoID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post repos repo ID cron params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostReposRepoIDCronParams) WithDefaults() *PostReposRepoIDCronParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post repos repo ID cron params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostReposRepoIDCronParams) SetDefaults() {
	var (
		authorizationDefault = string("Bearer <personal access token>")
	)

	val := PostReposRepoIDCronParams{
		Authorization: authorizationDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the post repos repo ID cron params
func (o *PostReposRepoIDCronParams) WithTimeout(timeout time.Duration) *PostReposRepoIDCronParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post repos repo ID cron params
func (o *PostReposRepoIDCronParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post repos repo ID cron params
func (o *PostReposRepoIDCronParams) WithContext(ctx context.Context) *PostReposRepoIDCronParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post repos repo ID cron params
func (o *PostReposRepoIDCronParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post repos repo ID cron params
func (o *PostReposRepoIDCronParams) WithHTTPClient(client *http.Client) *PostReposRepoIDCronParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post repos repo ID cron params
func (o *PostReposRepoIDCronParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the post repos repo ID cron params
func (o *PostReposRepoIDCronParams) WithAuthorization(authorization string) *PostReposRepoIDCronParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the post repos repo ID cron params
func (o *PostReposRepoIDCronParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithCronJob adds the cronJob to the post repos repo ID cron params
func (o *PostReposRepoIDCronParams) WithCronJob(cronJob *models.Cron) *PostReposRepoIDCronParams {
	o.SetCronJob(cronJob)
	return o
}

// SetCronJob adds the cronJob to the post repos repo ID cron params
func (o *PostReposRepoIDCronParams) SetCronJob(cronJob *models.Cron) {
	o.CronJob = cronJob
}

// WithRepoID adds the repoID to the post repos repo ID cron params
func (o *PostReposRepoIDCronParams) WithRepoID(repoID int64) *PostReposRepoIDCronParams {
	o.SetRepoID(repoID)
	return o
}

// SetRepoID adds the repoId to the post repos repo ID cron params
func (o *PostReposRepoIDCronParams) SetRepoID(repoID int64) {
	o.RepoID = repoID
}

// WriteToRequest writes these params to a swagger request
func (o *PostReposRepoIDCronParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}
	if o.CronJob != nil {
		if err := r.SetBodyParam(o.CronJob); err != nil {
			return err
		}
	}

	// path param repo_id
	if err := r.SetPathParam("repo_id", swag.FormatInt64(o.RepoID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
