# Credits to: https://github.com/vitejs/vite/blob/main/.github/ISSUE_TEMPLATE/bug_report.yml
name: "\U0001F41E Bug report"
description: Report an issue with Woodpecker
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component of Woodpecker is affected by the issue?
      multiple: true
      options:
        - server
        - agent
        - cli
        - web-ui
        - other
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: Bug description
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Install Woodpecker Server with the following configuration: ...
        2. Install Woodpecker Agent with the configuration below: ...
        3. Besides, set some settings in the forge: ...
        4. Run them all by the commands: ...
        5. Go to ..., click here and there, see next error: ...
        6. Also, check the logs and find this: ...
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: |
        When I click here and there, there should not be an error, but a successful operation.
        There should not be the errors in the logs, but the messages, that indicate a process: ...
    validations:
      required: false
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Output of `https://<your-woodpecker-instance>/version`
      render: shell
      placeholder: Version info, docker-compose config, Kubernetes manifests
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: |
        Logs? Screenshots? Anything that will give us more context about the issue you are encountering!
        Sometimes a picture is worth a thousand words, but please try not to insert an image of logs / text
        and copy paste the text instead.

        Tip: You can attach images by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Read the [docs](https://woodpecker-ci.org/docs/intro).
          required: true
        - label: Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
          required: true
        - label: Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/versions]
          required: true
