# docker build --rm -f docker/Dockerfile.cli -t woodpeckerci/woodpecker-cli .

# use golang image to copy ssl certs later
FROM golang:1.16

FROM scratch

# copy certs from golang:1.16 image
COPY --from=0 /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

ENV GODEBUG=netdns=go
ADD dist/cli/linux_amd64/woodpecker-cli /bin/

HEALTHCHECK CMD ["/bin/woodpecker-cli", "ping"]

ENTRYPOINT ["/bin/woodpecker-cli"]
