FROM --platform=$BUILDPLATFORM docker.io/golang:1.18 AS build

WORKDIR /src
COPY . .
ARG TARGETOS TARGETARCH
RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg \
    make build-cli

FROM docker.io/alpine:3.16
RUN apk add -U --no-cache ca-certificates
ENV GODEBUG=netdns=go

COPY --from=build /src/dist/woodpecker-cli /bin/

HEALTHCHECK CMD ["/bin/woodpecker-cli", "ping"]
ENTRYPOINT ["/bin/woodpecker-cli"]
