FROM --platform=$BUILDPLATFORM docker.io/golang:1.21 AS build

WORKDIR /src
COPY . .
ARG TARGETOS TARGETARCH CI_COMMIT_SHA CI_COMMIT_TAG CI_COMMIT_BRANCH
RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg \
    make build-agent

FROM docker.io/alpine:3.18
# renovate: datasource=repology depName=alpine_3_18/ca-certificates versioning=loose
ENV CA_CERTIFICATES_VERSION="20230506-r0"
RUN apk add -U --no-cache ca-certificates=${CA_CERTIFICATES_VERSION}
ENV GODEBUG=netdns=go
EXPOSE 3000

COPY --from=build /src/dist/woodpecker-agent /bin/
RUN mkdir -p /etc/woodpecker

HEALTHCHECK CMD ["/bin/woodpecker-agent", "ping"]
ENTRYPOINT ["/bin/woodpecker-agent"]
