# use golang image to copy ssl certs later
FROM golang:1.16

FROM scratch
ENV GODEBUG=netdns=go
EXPOSE 3000
HEALTHCHECK CMD ["/bin/woodpecker-cli", "ping"]

# copy certs from golang:1.16 image
COPY --from=0 /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

ADD ./woodpecker-cli /bin/

ENTRYPOINT ["/bin/woodpecker-cli"]
