# docker build --rm -f docker/Dockerfile.cli.alpine -t woodpeckerci/woodpecker-cli .

FROM alpine:3.14
RUN apk add -U --no-cache ca-certificates

ENV GODEBUG=netdns=go
ADD dist/cli/linux_amd64/woodpecker-cli /bin/

HEALTHCHECK CMD ["/bin/woodpecker-cli", "ping"]

ENTRYPOINT ["/bin/woodpecker-cli"]
