# docker build --rm  -f docker/Dockerfile.server.alpine -t woodpeckerci/woodpecker-server .

FROM alpine:3.14
RUN apk add -U --no-cache ca-certificates

EXPOSE 8000 9000 80 443

ENV GODEBUG=netdns=go
ENV WOODPECKER_DATABASE_DATASOURCE=/var/lib/woodpecker/woodpecker.sqlite
ENV WOODPECKER_DATABASE_DRIVER=sqlite3
ENV XDG_CACHE_HOME=/var/lib/woodpecker

ADD dist/server/linux_amd64/woodpecker-server /bin/

ENTRYPOINT ["/bin/woodpecker-server"]
