// Code generated by go-swagger; DO NOT EDIT.

package repository_secrets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"go.woodpecker-ci.org/woodpecker/v2/woodpecker-go/models"
)

// NewPatchReposRepoIDSecretsSecretNameParams creates a new PatchReposRepoIDSecretsSecretNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatchReposRepoIDSecretsSecretNameParams() *PatchReposRepoIDSecretsSecretNameParams {
	return &PatchReposRepoIDSecretsSecretNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPatchReposRepoIDSecretsSecretNameParamsWithTimeout creates a new PatchReposRepoIDSecretsSecretNameParams object
// with the ability to set a timeout on a request.
func NewPatchReposRepoIDSecretsSecretNameParamsWithTimeout(timeout time.Duration) *PatchReposRepoIDSecretsSecretNameParams {
	return &PatchReposRepoIDSecretsSecretNameParams{
		timeout: timeout,
	}
}

// NewPatchReposRepoIDSecretsSecretNameParamsWithContext creates a new PatchReposRepoIDSecretsSecretNameParams object
// with the ability to set a context for a request.
func NewPatchReposRepoIDSecretsSecretNameParamsWithContext(ctx context.Context) *PatchReposRepoIDSecretsSecretNameParams {
	return &PatchReposRepoIDSecretsSecretNameParams{
		Context: ctx,
	}
}

// NewPatchReposRepoIDSecretsSecretNameParamsWithHTTPClient creates a new PatchReposRepoIDSecretsSecretNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatchReposRepoIDSecretsSecretNameParamsWithHTTPClient(client *http.Client) *PatchReposRepoIDSecretsSecretNameParams {
	return &PatchReposRepoIDSecretsSecretNameParams{
		HTTPClient: client,
	}
}

/*
PatchReposRepoIDSecretsSecretNameParams contains all the parameters to send to the API endpoint

	for the patch repos repo ID secrets secret name operation.

	Typically these are written to a http.Request.
*/
type PatchReposRepoIDSecretsSecretNameParams struct {

	/* Authorization.

	   Insert your personal access token

	   Default: "Bearer \u003cpersonal access token\u003e"
	*/
	Authorization string

	/* RepoID.

	   the repository id
	*/
	RepoID int64

	/* Secret.

	   the secret itself
	*/
	Secret *models.Secret

	/* SecretName.

	   the secret name
	*/
	SecretName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the patch repos repo ID secrets secret name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchReposRepoIDSecretsSecretNameParams) WithDefaults() *PatchReposRepoIDSecretsSecretNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patch repos repo ID secrets secret name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchReposRepoIDSecretsSecretNameParams) SetDefaults() {
	var (
		authorizationDefault = string("Bearer <personal access token>")
	)

	val := PatchReposRepoIDSecretsSecretNameParams{
		Authorization: authorizationDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the patch repos repo ID secrets secret name params
func (o *PatchReposRepoIDSecretsSecretNameParams) WithTimeout(timeout time.Duration) *PatchReposRepoIDSecretsSecretNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch repos repo ID secrets secret name params
func (o *PatchReposRepoIDSecretsSecretNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch repos repo ID secrets secret name params
func (o *PatchReposRepoIDSecretsSecretNameParams) WithContext(ctx context.Context) *PatchReposRepoIDSecretsSecretNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch repos repo ID secrets secret name params
func (o *PatchReposRepoIDSecretsSecretNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch repos repo ID secrets secret name params
func (o *PatchReposRepoIDSecretsSecretNameParams) WithHTTPClient(client *http.Client) *PatchReposRepoIDSecretsSecretNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch repos repo ID secrets secret name params
func (o *PatchReposRepoIDSecretsSecretNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the patch repos repo ID secrets secret name params
func (o *PatchReposRepoIDSecretsSecretNameParams) WithAuthorization(authorization string) *PatchReposRepoIDSecretsSecretNameParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the patch repos repo ID secrets secret name params
func (o *PatchReposRepoIDSecretsSecretNameParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithRepoID adds the repoID to the patch repos repo ID secrets secret name params
func (o *PatchReposRepoIDSecretsSecretNameParams) WithRepoID(repoID int64) *PatchReposRepoIDSecretsSecretNameParams {
	o.SetRepoID(repoID)
	return o
}

// SetRepoID adds the repoId to the patch repos repo ID secrets secret name params
func (o *PatchReposRepoIDSecretsSecretNameParams) SetRepoID(repoID int64) {
	o.RepoID = repoID
}

// WithSecret adds the secret to the patch repos repo ID secrets secret name params
func (o *PatchReposRepoIDSecretsSecretNameParams) WithSecret(secret *models.Secret) *PatchReposRepoIDSecretsSecretNameParams {
	o.SetSecret(secret)
	return o
}

// SetSecret adds the secret to the patch repos repo ID secrets secret name params
func (o *PatchReposRepoIDSecretsSecretNameParams) SetSecret(secret *models.Secret) {
	o.Secret = secret
}

// WithSecretName adds the secretName to the patch repos repo ID secrets secret name params
func (o *PatchReposRepoIDSecretsSecretNameParams) WithSecretName(secretName string) *PatchReposRepoIDSecretsSecretNameParams {
	o.SetSecretName(secretName)
	return o
}

// SetSecretName adds the secretName to the patch repos repo ID secrets secret name params
func (o *PatchReposRepoIDSecretsSecretNameParams) SetSecretName(secretName string) {
	o.SecretName = secretName
}

// WriteToRequest writes these params to a swagger request
func (o *PatchReposRepoIDSecretsSecretNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// path param repo_id
	if err := r.SetPathParam("repo_id", swag.FormatInt64(o.RepoID)); err != nil {
		return err
	}
	if o.Secret != nil {
		if err := r.SetBodyParam(o.Secret); err != nil {
			return err
		}
	}

	// path param secretName
	if err := r.SetPathParam("secretName", o.SecretName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
