// Code generated by go-swagger; DO NOT EDIT.

package orgs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"go.woodpecker-ci.org/woodpecker/v2/woodpecker-go/models"
)

// GetOrgsReader is a Reader for the GetOrgs structure.
type GetOrgsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOrgsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetOrgsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /orgs] GetOrgs", response, response.Code())
	}
}

// NewGetOrgsOK creates a GetOrgsOK with default headers values
func NewGetOrgsOK() *GetOrgsOK {
	return &GetOrgsOK{}
}

/*
GetOrgsOK describes a response with status code 200, with default header values.

OK
*/
type GetOrgsOK struct {
	Payload []*models.Org
}

// IsSuccess returns true when this get orgs o k response has a 2xx status code
func (o *GetOrgsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get orgs o k response has a 3xx status code
func (o *GetOrgsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get orgs o k response has a 4xx status code
func (o *GetOrgsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get orgs o k response has a 5xx status code
func (o *GetOrgsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get orgs o k response a status code equal to that given
func (o *GetOrgsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get orgs o k response
func (o *GetOrgsOK) Code() int {
	return 200
}

func (o *GetOrgsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /orgs][%d] getOrgsOK %s", 200, payload)
}

func (o *GetOrgsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /orgs][%d] getOrgsOK %s", 200, payload)
}

func (o *GetOrgsOK) GetPayload() []*models.Org {
	return o.Payload
}

func (o *GetOrgsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
