// Code generated by go-swagger; DO NOT EDIT.

package pipeline_queues

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"go.woodpecker-ci.org/woodpecker/v2/woodpecker-go/models"
)

// GetPipelinesReader is a Reader for the GetPipelines structure.
type GetPipelinesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPipelinesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPipelinesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /pipelines] GetPipelines", response, response.Code())
	}
}

// NewGetPipelinesOK creates a GetPipelinesOK with default headers values
func NewGetPipelinesOK() *GetPipelinesOK {
	return &GetPipelinesOK{}
}

/*
GetPipelinesOK describes a response with status code 200, with default header values.

OK
*/
type GetPipelinesOK struct {
	Payload []*models.Feed
}

// IsSuccess returns true when this get pipelines o k response has a 2xx status code
func (o *GetPipelinesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get pipelines o k response has a 3xx status code
func (o *GetPipelinesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get pipelines o k response has a 4xx status code
func (o *GetPipelinesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get pipelines o k response has a 5xx status code
func (o *GetPipelinesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get pipelines o k response a status code equal to that given
func (o *GetPipelinesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get pipelines o k response
func (o *GetPipelinesOK) Code() int {
	return 200
}

func (o *GetPipelinesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /pipelines][%d] getPipelinesOK %s", 200, payload)
}

func (o *GetPipelinesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /pipelines][%d] getPipelinesOK %s", 200, payload)
}

func (o *GetPipelinesOK) GetPayload() []*models.Feed {
	return o.Payload
}

func (o *GetPipelinesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
