// Code generated by go-swagger; DO NOT EDIT.

package pipeline_queues

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostQueuePauseParams creates a new PostQueuePauseParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostQueuePauseParams() *PostQueuePauseParams {
	return &PostQueuePauseParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostQueuePauseParamsWithTimeout creates a new PostQueuePauseParams object
// with the ability to set a timeout on a request.
func NewPostQueuePauseParamsWithTimeout(timeout time.Duration) *PostQueuePauseParams {
	return &PostQueuePauseParams{
		timeout: timeout,
	}
}

// NewPostQueuePauseParamsWithContext creates a new PostQueuePauseParams object
// with the ability to set a context for a request.
func NewPostQueuePauseParamsWithContext(ctx context.Context) *PostQueuePauseParams {
	return &PostQueuePauseParams{
		Context: ctx,
	}
}

// NewPostQueuePauseParamsWithHTTPClient creates a new PostQueuePauseParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostQueuePauseParamsWithHTTPClient(client *http.Client) *PostQueuePauseParams {
	return &PostQueuePauseParams{
		HTTPClient: client,
	}
}

/*
PostQueuePauseParams contains all the parameters to send to the API endpoint

	for the post queue pause operation.

	Typically these are written to a http.Request.
*/
type PostQueuePauseParams struct {

	/* Authorization.

	   Insert your personal access token

	   Default: "Bearer \u003cpersonal access token\u003e"
	*/
	Authorization string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post queue pause params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostQueuePauseParams) WithDefaults() *PostQueuePauseParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post queue pause params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostQueuePauseParams) SetDefaults() {
	var (
		authorizationDefault = string("Bearer <personal access token>")
	)

	val := PostQueuePauseParams{
		Authorization: authorizationDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the post queue pause params
func (o *PostQueuePauseParams) WithTimeout(timeout time.Duration) *PostQueuePauseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post queue pause params
func (o *PostQueuePauseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post queue pause params
func (o *PostQueuePauseParams) WithContext(ctx context.Context) *PostQueuePauseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post queue pause params
func (o *PostQueuePauseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post queue pause params
func (o *PostQueuePauseParams) WithHTTPClient(client *http.Client) *PostQueuePauseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post queue pause params
func (o *PostQueuePauseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the post queue pause params
func (o *PostQueuePauseParams) WithAuthorization(authorization string) *PostQueuePauseParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the post queue pause params
func (o *PostQueuePauseParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WriteToRequest writes these params to a swagger request
func (o *PostQueuePauseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
