// Code generated by go-swagger; DO NOT EDIT.

package pipeline_queues

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostQueuePauseReader is a Reader for the PostQueuePause structure.
type PostQueuePauseReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostQueuePauseReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewPostQueuePauseNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /queue/pause] PostQueuePause", response, response.Code())
	}
}

// NewPostQueuePauseNoContent creates a PostQueuePauseNoContent with default headers values
func NewPostQueuePauseNoContent() *PostQueuePauseNoContent {
	return &PostQueuePauseNoContent{}
}

/*
PostQueuePauseNoContent describes a response with status code 204, with default header values.

No Content
*/
type PostQueuePauseNoContent struct {
}

// IsSuccess returns true when this post queue pause no content response has a 2xx status code
func (o *PostQueuePauseNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post queue pause no content response has a 3xx status code
func (o *PostQueuePauseNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post queue pause no content response has a 4xx status code
func (o *PostQueuePauseNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this post queue pause no content response has a 5xx status code
func (o *PostQueuePauseNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this post queue pause no content response a status code equal to that given
func (o *PostQueuePauseNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the post queue pause no content response
func (o *PostQueuePauseNoContent) Code() int {
	return 204
}

func (o *PostQueuePauseNoContent) Error() string {
	return fmt.Sprintf("[POST /queue/pause][%d] postQueuePauseNoContent", 204)
}

func (o *PostQueuePauseNoContent) String() string {
	return fmt.Sprintf("[POST /queue/pause][%d] postQueuePauseNoContent", 204)
}

func (o *PostQueuePauseNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
