// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Org org
//
// swagger:model Org
type Org struct {

	// forge id
	ForgeID int64 `json:"forge_id,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// is user
	IsUser bool `json:"is_user,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this org
func (m *Org) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this org based on context it is used
func (m *Org) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Org) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Org) UnmarshalBinary(b []byte) error {
	var res Org
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
