// Code generated by go-swagger; DO NOT EDIT.

package repository_registries

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetReposRepoIDRegistryParams creates a new GetReposRepoIDRegistryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetReposRepoIDRegistryParams() *GetReposRepoIDRegistryParams {
	return &GetReposRepoIDRegistryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetReposRepoIDRegistryParamsWithTimeout creates a new GetReposRepoIDRegistryParams object
// with the ability to set a timeout on a request.
func NewGetReposRepoIDRegistryParamsWithTimeout(timeout time.Duration) *GetReposRepoIDRegistryParams {
	return &GetReposRepoIDRegistryParams{
		timeout: timeout,
	}
}

// NewGetReposRepoIDRegistryParamsWithContext creates a new GetReposRepoIDRegistryParams object
// with the ability to set a context for a request.
func NewGetReposRepoIDRegistryParamsWithContext(ctx context.Context) *GetReposRepoIDRegistryParams {
	return &GetReposRepoIDRegistryParams{
		Context: ctx,
	}
}

// NewGetReposRepoIDRegistryParamsWithHTTPClient creates a new GetReposRepoIDRegistryParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetReposRepoIDRegistryParamsWithHTTPClient(client *http.Client) *GetReposRepoIDRegistryParams {
	return &GetReposRepoIDRegistryParams{
		HTTPClient: client,
	}
}

/*
GetReposRepoIDRegistryParams contains all the parameters to send to the API endpoint

	for the get repos repo ID registry operation.

	Typically these are written to a http.Request.
*/
type GetReposRepoIDRegistryParams struct {

	/* Authorization.

	   Insert your personal access token

	   Default: "Bearer \u003cpersonal access token\u003e"
	*/
	Authorization string

	/* Page.

	   for response pagination, page offset number

	   Default: 1
	*/
	Page *int64

	/* PerPage.

	   for response pagination, max items per page

	   Default: 50
	*/
	PerPage *int64

	/* RepoID.

	   the repository id
	*/
	RepoID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get repos repo ID registry params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetReposRepoIDRegistryParams) WithDefaults() *GetReposRepoIDRegistryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get repos repo ID registry params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetReposRepoIDRegistryParams) SetDefaults() {
	var (
		authorizationDefault = string("Bearer <personal access token>")

		pageDefault = int64(1)

		perPageDefault = int64(50)
	)

	val := GetReposRepoIDRegistryParams{
		Authorization: authorizationDefault,
		Page:          &pageDefault,
		PerPage:       &perPageDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get repos repo ID registry params
func (o *GetReposRepoIDRegistryParams) WithTimeout(timeout time.Duration) *GetReposRepoIDRegistryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get repos repo ID registry params
func (o *GetReposRepoIDRegistryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get repos repo ID registry params
func (o *GetReposRepoIDRegistryParams) WithContext(ctx context.Context) *GetReposRepoIDRegistryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get repos repo ID registry params
func (o *GetReposRepoIDRegistryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get repos repo ID registry params
func (o *GetReposRepoIDRegistryParams) WithHTTPClient(client *http.Client) *GetReposRepoIDRegistryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get repos repo ID registry params
func (o *GetReposRepoIDRegistryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the get repos repo ID registry params
func (o *GetReposRepoIDRegistryParams) WithAuthorization(authorization string) *GetReposRepoIDRegistryParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the get repos repo ID registry params
func (o *GetReposRepoIDRegistryParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithPage adds the page to the get repos repo ID registry params
func (o *GetReposRepoIDRegistryParams) WithPage(page *int64) *GetReposRepoIDRegistryParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get repos repo ID registry params
func (o *GetReposRepoIDRegistryParams) SetPage(page *int64) {
	o.Page = page
}

// WithPerPage adds the perPage to the get repos repo ID registry params
func (o *GetReposRepoIDRegistryParams) WithPerPage(perPage *int64) *GetReposRepoIDRegistryParams {
	o.SetPerPage(perPage)
	return o
}

// SetPerPage adds the perPage to the get repos repo ID registry params
func (o *GetReposRepoIDRegistryParams) SetPerPage(perPage *int64) {
	o.PerPage = perPage
}

// WithRepoID adds the repoID to the get repos repo ID registry params
func (o *GetReposRepoIDRegistryParams) WithRepoID(repoID int64) *GetReposRepoIDRegistryParams {
	o.SetRepoID(repoID)
	return o
}

// SetRepoID adds the repoId to the get repos repo ID registry params
func (o *GetReposRepoIDRegistryParams) SetRepoID(repoID int64) {
	o.RepoID = repoID
}

// WriteToRequest writes these params to a swagger request
func (o *GetReposRepoIDRegistryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if o.Page != nil {

		// query param page
		var qrPage int64

		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt64(qrPage)
		if qPage != "" {

			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}
	}

	if o.PerPage != nil {

		// query param perPage
		var qrPerPage int64

		if o.PerPage != nil {
			qrPerPage = *o.PerPage
		}
		qPerPage := swag.FormatInt64(qrPerPage)
		if qPerPage != "" {

			if err := r.SetQueryParam("perPage", qPerPage); err != nil {
				return err
			}
		}
	}

	// path param repo_id
	if err := r.SetPathParam("repo_id", swag.FormatInt64(o.RepoID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
