// Code generated by go-swagger; DO NOT EDIT.

package repository_registries

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetReposRepoIDRegistryRegistryParams creates a new GetReposRepoIDRegistryRegistryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetReposRepoIDRegistryRegistryParams() *GetReposRepoIDRegistryRegistryParams {
	return &GetReposRepoIDRegistryRegistryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetReposRepoIDRegistryRegistryParamsWithTimeout creates a new GetReposRepoIDRegistryRegistryParams object
// with the ability to set a timeout on a request.
func NewGetReposRepoIDRegistryRegistryParamsWithTimeout(timeout time.Duration) *GetReposRepoIDRegistryRegistryParams {
	return &GetReposRepoIDRegistryRegistryParams{
		timeout: timeout,
	}
}

// NewGetReposRepoIDRegistryRegistryParamsWithContext creates a new GetReposRepoIDRegistryRegistryParams object
// with the ability to set a context for a request.
func NewGetReposRepoIDRegistryRegistryParamsWithContext(ctx context.Context) *GetReposRepoIDRegistryRegistryParams {
	return &GetReposRepoIDRegistryRegistryParams{
		Context: ctx,
	}
}

// NewGetReposRepoIDRegistryRegistryParamsWithHTTPClient creates a new GetReposRepoIDRegistryRegistryParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetReposRepoIDRegistryRegistryParamsWithHTTPClient(client *http.Client) *GetReposRepoIDRegistryRegistryParams {
	return &GetReposRepoIDRegistryRegistryParams{
		HTTPClient: client,
	}
}

/*
GetReposRepoIDRegistryRegistryParams contains all the parameters to send to the API endpoint

	for the get repos repo ID registry registry operation.

	Typically these are written to a http.Request.
*/
type GetReposRepoIDRegistryRegistryParams struct {

	/* Authorization.

	   Insert your personal access token

	   Default: "Bearer \u003cpersonal access token\u003e"
	*/
	Authorization string

	/* Registry.

	   the registry name
	*/
	Registry string

	/* RepoID.

	   the repository id
	*/
	RepoID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get repos repo ID registry registry params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetReposRepoIDRegistryRegistryParams) WithDefaults() *GetReposRepoIDRegistryRegistryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get repos repo ID registry registry params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetReposRepoIDRegistryRegistryParams) SetDefaults() {
	var (
		authorizationDefault = string("Bearer <personal access token>")
	)

	val := GetReposRepoIDRegistryRegistryParams{
		Authorization: authorizationDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get repos repo ID registry registry params
func (o *GetReposRepoIDRegistryRegistryParams) WithTimeout(timeout time.Duration) *GetReposRepoIDRegistryRegistryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get repos repo ID registry registry params
func (o *GetReposRepoIDRegistryRegistryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get repos repo ID registry registry params
func (o *GetReposRepoIDRegistryRegistryParams) WithContext(ctx context.Context) *GetReposRepoIDRegistryRegistryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get repos repo ID registry registry params
func (o *GetReposRepoIDRegistryRegistryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get repos repo ID registry registry params
func (o *GetReposRepoIDRegistryRegistryParams) WithHTTPClient(client *http.Client) *GetReposRepoIDRegistryRegistryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get repos repo ID registry registry params
func (o *GetReposRepoIDRegistryRegistryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the get repos repo ID registry registry params
func (o *GetReposRepoIDRegistryRegistryParams) WithAuthorization(authorization string) *GetReposRepoIDRegistryRegistryParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the get repos repo ID registry registry params
func (o *GetReposRepoIDRegistryRegistryParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithRegistry adds the registry to the get repos repo ID registry registry params
func (o *GetReposRepoIDRegistryRegistryParams) WithRegistry(registry string) *GetReposRepoIDRegistryRegistryParams {
	o.SetRegistry(registry)
	return o
}

// SetRegistry adds the registry to the get repos repo ID registry registry params
func (o *GetReposRepoIDRegistryRegistryParams) SetRegistry(registry string) {
	o.Registry = registry
}

// WithRepoID adds the repoID to the get repos repo ID registry registry params
func (o *GetReposRepoIDRegistryRegistryParams) WithRepoID(repoID int64) *GetReposRepoIDRegistryRegistryParams {
	o.SetRepoID(repoID)
	return o
}

// SetRepoID adds the repoId to the get repos repo ID registry registry params
func (o *GetReposRepoIDRegistryRegistryParams) SetRepoID(repoID int64) {
	o.RepoID = repoID
}

// WriteToRequest writes these params to a swagger request
func (o *GetReposRepoIDRegistryRegistryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// path param registry
	if err := r.SetPathParam("registry", o.Registry); err != nil {
		return err
	}

	// path param repo_id
	if err := r.SetPathParam("repo_id", swag.FormatInt64(o.RepoID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
