// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"go.woodpecker-ci.org/woodpecker/v3/server/services/encryption/types"
)

// NewMockEncryptionServiceBuilder creates a new instance of MockEncryptionServiceBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEncryptionServiceBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEncryptionServiceBuilder {
	mock := &MockEncryptionServiceBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEncryptionServiceBuilder is an autogenerated mock type for the EncryptionServiceBuilder type
type MockEncryptionServiceBuilder struct {
	mock.Mock
}

type MockEncryptionServiceBuilder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEncryptionServiceBuilder) EXPECT() *MockEncryptionServiceBuilder_Expecter {
	return &MockEncryptionServiceBuilder_Expecter{mock: &_m.Mock}
}

// Build provides a mock function for the type MockEncryptionServiceBuilder
func (_mock *MockEncryptionServiceBuilder) Build() (types.EncryptionService, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Build")
	}

	var r0 types.EncryptionService
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (types.EncryptionService, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() types.EncryptionService); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.EncryptionService)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEncryptionServiceBuilder_Build_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Build'
type MockEncryptionServiceBuilder_Build_Call struct {
	*mock.Call
}

// Build is a helper method to define mock.On call
func (_e *MockEncryptionServiceBuilder_Expecter) Build() *MockEncryptionServiceBuilder_Build_Call {
	return &MockEncryptionServiceBuilder_Build_Call{Call: _e.mock.On("Build")}
}

func (_c *MockEncryptionServiceBuilder_Build_Call) Run(run func()) *MockEncryptionServiceBuilder_Build_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEncryptionServiceBuilder_Build_Call) Return(encryptionService types.EncryptionService, err error) *MockEncryptionServiceBuilder_Build_Call {
	_c.Call.Return(encryptionService, err)
	return _c
}

func (_c *MockEncryptionServiceBuilder_Build_Call) RunAndReturn(run func() (types.EncryptionService, error)) *MockEncryptionServiceBuilder_Build_Call {
	_c.Call.Return(run)
	return _c
}

// WithClients provides a mock function for the type MockEncryptionServiceBuilder
func (_mock *MockEncryptionServiceBuilder) WithClients(clients []types.EncryptionClient) types.EncryptionServiceBuilder {
	ret := _mock.Called(clients)

	if len(ret) == 0 {
		panic("no return value specified for WithClients")
	}

	var r0 types.EncryptionServiceBuilder
	if returnFunc, ok := ret.Get(0).(func([]types.EncryptionClient) types.EncryptionServiceBuilder); ok {
		r0 = returnFunc(clients)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.EncryptionServiceBuilder)
		}
	}
	return r0
}

// MockEncryptionServiceBuilder_WithClients_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithClients'
type MockEncryptionServiceBuilder_WithClients_Call struct {
	*mock.Call
}

// WithClients is a helper method to define mock.On call
//   - clients []types.EncryptionClient
func (_e *MockEncryptionServiceBuilder_Expecter) WithClients(clients interface{}) *MockEncryptionServiceBuilder_WithClients_Call {
	return &MockEncryptionServiceBuilder_WithClients_Call{Call: _e.mock.On("WithClients", clients)}
}

func (_c *MockEncryptionServiceBuilder_WithClients_Call) Run(run func(clients []types.EncryptionClient)) *MockEncryptionServiceBuilder_WithClients_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []types.EncryptionClient
		if args[0] != nil {
			arg0 = args[0].([]types.EncryptionClient)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEncryptionServiceBuilder_WithClients_Call) Return(encryptionServiceBuilder types.EncryptionServiceBuilder) *MockEncryptionServiceBuilder_WithClients_Call {
	_c.Call.Return(encryptionServiceBuilder)
	return _c
}

func (_c *MockEncryptionServiceBuilder_WithClients_Call) RunAndReturn(run func(clients []types.EncryptionClient) types.EncryptionServiceBuilder) *MockEncryptionServiceBuilder_WithClients_Call {
	_c.Call.Return(run)
	return _c
}
