when:
  - event: [push, pull_request]
    branch: main

matrix:
  GO_VERSION:
    - '1.22'
    - '1.24'
    - 'latest'

steps:
  - name: test
    image: golang:${GO_VERSION}
    commands:
      - go test -v --cover ./...