// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	proto "go.woodpecker-ci.org/woodpecker/v3/pipeline/rpc/proto"
)

// MockWoodpeckerAuthServer is an autogenerated mock type for the WoodpeckerAuthServer type
type MockWoodpeckerAuthServer struct {
	mock.Mock
}

type MockWoodpeckerAuthServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWoodpeckerAuthServer) EXPECT() *MockWoodpeckerAuthServer_Expecter {
	return &MockWoodpeckerAuthServer_Expecter{mock: &_m.Mock}
}

// Auth provides a mock function with given fields: _a0, _a1
func (_m *MockWoodpeckerAuthServer) Auth(_a0 context.Context, _a1 *proto.AuthRequest) (*proto.AuthResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Auth")
	}

	var r0 *proto.AuthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.AuthRequest) (*proto.AuthResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.AuthRequest) *proto.AuthResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.AuthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.AuthRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWoodpeckerAuthServer_Auth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Auth'
type MockWoodpeckerAuthServer_Auth_Call struct {
	*mock.Call
}

// Auth is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *proto.AuthRequest
func (_e *MockWoodpeckerAuthServer_Expecter) Auth(_a0 interface{}, _a1 interface{}) *MockWoodpeckerAuthServer_Auth_Call {
	return &MockWoodpeckerAuthServer_Auth_Call{Call: _e.mock.On("Auth", _a0, _a1)}
}

func (_c *MockWoodpeckerAuthServer_Auth_Call) Run(run func(_a0 context.Context, _a1 *proto.AuthRequest)) *MockWoodpeckerAuthServer_Auth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*proto.AuthRequest))
	})
	return _c
}

func (_c *MockWoodpeckerAuthServer_Auth_Call) Return(_a0 *proto.AuthResponse, _a1 error) *MockWoodpeckerAuthServer_Auth_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWoodpeckerAuthServer_Auth_Call) RunAndReturn(run func(context.Context, *proto.AuthRequest) (*proto.AuthResponse, error)) *MockWoodpeckerAuthServer_Auth_Call {
	_c.Call.Return(run)
	return _c
}

// mustEmbedUnimplementedWoodpeckerAuthServer provides a mock function with no fields
func (_m *MockWoodpeckerAuthServer) mustEmbedUnimplementedWoodpeckerAuthServer() {
	_m.Called()
}

// MockWoodpeckerAuthServer_mustEmbedUnimplementedWoodpeckerAuthServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedWoodpeckerAuthServer'
type MockWoodpeckerAuthServer_mustEmbedUnimplementedWoodpeckerAuthServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedWoodpeckerAuthServer is a helper method to define mock.On call
func (_e *MockWoodpeckerAuthServer_Expecter) mustEmbedUnimplementedWoodpeckerAuthServer() *MockWoodpeckerAuthServer_mustEmbedUnimplementedWoodpeckerAuthServer_Call {
	return &MockWoodpeckerAuthServer_mustEmbedUnimplementedWoodpeckerAuthServer_Call{Call: _e.mock.On("mustEmbedUnimplementedWoodpeckerAuthServer")}
}

func (_c *MockWoodpeckerAuthServer_mustEmbedUnimplementedWoodpeckerAuthServer_Call) Run(run func()) *MockWoodpeckerAuthServer_mustEmbedUnimplementedWoodpeckerAuthServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWoodpeckerAuthServer_mustEmbedUnimplementedWoodpeckerAuthServer_Call) Return() *MockWoodpeckerAuthServer_mustEmbedUnimplementedWoodpeckerAuthServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWoodpeckerAuthServer_mustEmbedUnimplementedWoodpeckerAuthServer_Call) RunAndReturn(run func()) *MockWoodpeckerAuthServer_mustEmbedUnimplementedWoodpeckerAuthServer_Call {
	_c.Run(run)
	return _c
}

// NewMockWoodpeckerAuthServer creates a new instance of MockWoodpeckerAuthServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWoodpeckerAuthServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWoodpeckerAuthServer {
	mock := &MockWoodpeckerAuthServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
