workspace:
  base: /go
  path: src/github.com/drone/envsubst

clone:
  git:
    image: plugins/git
    depth: 50

pipeline:

  # these steps define a parallel execution
  # group and will fan out.

  foo:
    image: golang:1.7
    group: build
    commands:
      - echo step 1
      - sleep 10
      - echo done 1
  bar:
    image: golang:1.7
    group: build
    commands:
      - echo step 2
      - sleep 10
      - echo done 2

  # this step is not grouped with the previous
  # steps, resulting in a fan-in.

  baz:
    image: golang:1.7
    commands:
      - echo I should execute last.
      - echo after the prior two steps finish execution.

  # these steps define a parallel execution
  # group and will fan back out.

  qux:
    image: golang:1.7
    group: test
    commands:
      - echo step 3
      - sleep 10
      - echo done 3
  quux:
    image: golang:1.7
    group: test
    commands:
      - echo step 4
      - sleep 10
      - echo done 4
