when:
  - branch: [master, deploy]
    event: push
    path:
      - "folder/**"
      - "**/*.c"
  - tag: "v**"
    event: tag
  - event: cron
    cron:
      include:
        - hello

pipeline:
  echo:
    image: alpine
    commands:
      - echo "test"
