when:
  - branch: [main, deploy]
    event: push
    path:
      - 'folder/**'
      - '**/*.c'
  - tag: 'v**'
    event: tag
  - event: cron
    cron:
      include:
        - hello
  - event:
      exclude: pull_request_closed
    evaluate: 'CI_COMMIT_AUTHOR == "woodpecker-ci"'
  - event:
      exclude: pull_request_edited
    evaluate: 'CI_COMMIT_AUTHOR == "woodpecker-ci"'

steps:
  echo:
    image: alpine
    commands:
      - echo "test"
