steps:
  image:
    image: golang
    commands:
      - go test

  image-pull:
    image: golang
    pull: true
    commands:
      - go test

  single-command:
    image: golang
    commands: go test

  entrypoint:
    image: alpine
    entrypoint: ['some_entry', '--some-flag']

  single-entrypoint:
    image: alpine
    entrypoint: some_entry

  commands:
    privileged: true
    image: golang
    commands:
      - go get
      - go test

  environment:
    image: golang
    environment:
      CGO: 0
      GOOS: linux
      GOARCH: amd64
    commands:
      - go test

  secrets:
    image: docker
    commands:
      - echo $DOCKER_USERNAME
      - echo $DOCKER_PASSWORD
    secrets:
      - docker_username
      - docker_prod_password

  detached:
    image: redis
    detach: true

  volume:
    image: docker
    commands:
      - docker build --rm -t octocat/hello-world .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
