when:
  - event: tag
  - event: pull_request
    branch: ${CI_REPO_DEFAULT_BRANCH}
    path:
      - Makefile
      - .woodpecker/binaries.yaml

variables:
  - &golang_image 'docker.io/golang:1.25'
  - &node_image 'docker.io/node:24-alpine'
  - &xgo_image 'docker.io/techknowlogick/xgo:go-1.25.x'

# cspell:words bindata netgo

steps:
  build-web:
    image: *node_image
    directory: web/
    commands:
      - corepack enable
      - pnpm install --frozen-lockfile
      - pnpm build

  vendor:
    image: *golang_image
    commands:
      - go mod vendor

  cross-compile-server:
    depends_on:
      - vendor
      - build-web
    image: *xgo_image
    pull: true
    commands:
      - apt update
      - apt install -y tree
      - make cross-compile-server
    environment:
      PLATFORMS: linux|arm64/v8;linux|amd64;linux|riscv64;windows|amd64
      TAGS: bindata sqlite sqlite_unlock_notify netgo
      ARCHIVE_IT: '1'

  build-tarball:
    depends_on:
      - vendor
      - build-web
    image: *golang_image
    commands:
      - make build-tarball

  build-agent:
    depends_on:
      - vendor
    image: *golang_image
    commands:
      - apt update
      - apt install -y zip
      - make release-agent

  build-cli:
    depends_on:
      - vendor
    image: *golang_image
    commands:
      - apt update
      - apt install -y zip
      - make release-cli

  build-deb-rpm:
    depends_on:
      - cross-compile-server
      - build-agent
      - build-cli
    image: *golang_image
    commands:
      - make bundle

  build-sbom-trivy: # same as make sbom-trivy
    depends_on:
      - vendor
      - build-web
    image: ghcr.io/aquasecurity/trivy
    commands:
      - mkdir -p dist
      - trivy fs --scanners license --license-full --format spdx-json -o dist/base.go.spdx.json go.mod
      - trivy fs --scanners license --license-full --format spdx-json -o dist/webui.spdx.json web/

  build-sbom-syft: # same as make sbom-syft
    depends_on:
      - cross-compile-server
      - build-agent
      - build-cli
    image: *golang_image
    commands:
      - curl -sSfL https://get.anchore.io/syft | sh -s -- -b /usr/local/bin
      - syft scan file:dist/server/linux_amd64/woodpecker-server -o spdx-json > dist/server-deps.spdx.json
      - syft scan file:dist/agent/linux_amd64/woodpecker-agent -o spdx-json   > dist/agent-deps.spdx.json
      - syft scan file:dist/cli/linux_amd64/woodpecker-cli -o spdx-json       > dist/cli-deps.spdx.json

  build-sbom:
    depends_on:
      - build-sbom-trivy
      - build-sbom-syft
    image: *golang_image
    commands:
      - apt update; apt install -y jq
      - make sbom-calc sbom-clean

  checksums:
    depends_on:
      - cross-compile-server
      - build-agent
      - build-cli
      - build-deb-rpm
      - build-tarball
      - build-sbom
    image: *golang_image
    commands:
      - make release-checksums

  release-dryrun:
    depends_on:
      - checksums
    image: *golang_image
    commands:
      - ls -la dist/*.*
      - cat dist/checksums.txt

  release:
    depends_on:
      - checksums
    image: woodpeckerci/plugin-release:0.2.6
    settings:
      api_key:
        from_secret: github_token
      files:
        - dist/*.tar.gz
        - dist/*.zip
        - dist/*.deb
        - dist/*.rpm
        - dist/*.spdx.json
        - dist/checksums.txt
      title: ${CI_COMMIT_TAG##v}
    when:
      event: tag
