clone:
  git:
    image: plugins/git:next

pipeline:
  release:
    image: quay.io/helmpack/chart-releaser:v1.2.1
    secrets:
      - source: github_token
        target: CR_TOKEN
    commands:
      - sed -i "s/<version>/${DRONE_TAG##v}/g" charts/woodpecker-agent/Chart.yaml
      - sed -i "s/<version>/${DRONE_TAG##v}/g" charts/woodpecker-server/Chart.yaml
      - cat charts/woodpecker-agent/Chart.yaml
      - cat charts/woodpecker-server/Chart.yaml
      - mkdir -p .cr-index
      - cr package charts/woodpecker-server
      - cr package charts/woodpecker-agent
      - cr upload --owner woodpecker-ci --git-repo woodpecker-ci.github.io --release-name-template "helm-{{ .Name }}-{{ .Version }}"
      - cr index --owner woodpecker-ci --git-repo woodpecker-ci.github.io --pages-branch main --charts-repo https://woodpecker-ci.github.io --push --release-name-template "helm-{{ .Name }}-{{ .Version }}"
    when:
      event: tag

  lint:
    image: alpine/helm:3.5.3
    commands:
      # set some dummy versions so we can lint the helm-charts
      - sed -i "s/<version>/0.0.0/g" charts/woodpecker-agent/Chart.yaml
      - sed -i "s/<version>/0.0.0/g" charts/woodpecker-server/Chart.yaml
      - helm lint charts/woodpecker-agent/
      - helm lint charts/woodpecker-server/
    when:
      event: tag

depends_on:
  - release
