variables:
  - &golang_image 'docker.io/golang:1.26'
  - &when
    - path: &when_path # related config files
        - '.woodpecker/integration.yaml'
        # go source code
        - '**/*.go'
        - 'go.*'
      event: pull_request

when:
  - event: pull_request
  - event: push
    branch: ${CI_REPO_DEFAULT_BRANCH}
    path: *when_path

steps:
  - name: integration
    image: *golang_image
    commands:
      - go test -race -cover -coverprofile integration.out -timeout 60s -tags 'test' ./test/integration/...
    when:
      - path: *when_path

services:
  gitea:
    image: docker.io/gitea/gitea:1.25.4
    ports:
      - '8000'
    environment:
      USER_UID: 1000
      USER_GID: 1000
      # GITEA__server__DOMAIN: gitea.local.self
      GITEA__server__ROOT_URL: http://gitea:8000/
      GITEA__database__DB_TYPE: sqlite
      GITEA__database__HOST: gitea-database:5432
      GITEA__database__NAME: gitea
      GITEA__database__USER: gitea
      GITEA__database__PASSWD: 123456
      GITEA__webhook__ALLOWED_HOST_LIST: '*'
      GITEA__security__INSTALL_LOCK: 'true'
      GITEA__security__INTERNAL_TOKEN: '123456'
    when: *when
