clone:
  git:
    image: plugins/git:next

pipeline:
  build-frontend:
    image: node:10.17.0-stretch
    commands:
      - make build-frontend

  build:
    image: golang:1.16
    commands:
      - go get github.com/woodpecker-ci/togo
      - (cd web/; go generate ./...)
      - make release

  # publish-server-alpine:
  #   image: plugins/docker
  #   repo: woodpeckerci/woodpecker-server
  #   dockerfile: Dockerfile.alpine
  #   secrets: [ docker_username, docker_password ]
  #   tag: [ alpine ]
  #   when:
  #     branch: master
  #     event: push

  build-cli:
    image: golang:1.16
    commands: make release-cli

  publish-server:
    image: plugins/docker
    repo: woodpeckerci/woodpecker-server
    secrets: [docker_username, docker_password]
    tag: [latest]
    when:
      branch: master
      event: push

  publish-agent:
    image: plugins/docker
    repo: woodpeckerci/woodpecker-agent
    dockerfile: Dockerfile.agent
    secrets: [docker_username, docker_password]
    tag: [latest]
    when:
      branch: master
      event: push

  # publish-agent-alpine:
  #   image: plugins/docker
  #   repo: woodpeckerci/woodpecker-agent
  #   dockerfile: Dockerfile.agent.alpine
  #   secrets: [ docker_username, docker_password ]
  #   tag: [ alpine ]
  #   when:
  #     branch: master
  #     event: push

  # release-server-alpine:
  #   image: plugins/docker
  #   repo: woodpeckerci/woodpecker-server
  #   dockerfile: Dockerfile.alpine
  #   secrets: [ docker_username, docker_password ]
  #   tag: "${DRONE_TAG}-alpine"
  #   when:
  #     event: tag
  #
  # release-agent-alpine:
  #   image: plugins/docker
  #   repo: woodpeckerci/woodpecker-agent
  #   dockerfile: Dockerfile.agent.alpine
  #   secrets: [ docker_username, docker_password ]
  #   tag: "${DRONE_TAG}-alpine"
  #   when:
  #     event: tag

  release-server:
    image: plugins/docker
    repo: woodpeckerci/woodpecker-server
    secrets: [docker_username, docker_password]
    tag: ${DRONE_TAG}
    when:
      event: tag

  release-agent:
    image: plugins/docker
    repo: woodpeckerci/woodpecker-agent
    dockerfile: Dockerfile.agent
    secrets: [docker_username, docker_password]
    tag: ${DRONE_TAG}
    when:
      event: tag

  release-cli:
    image: plugins/github-release
    files:
      - cli/release/woodpecker_*.tar.gz
      - cli/release/woodpecker_checksums.txt
    secrets:
      - source: github_token
        target: github_release_api_key
    when:
      event: tag

depends_on:
  - test
