clone:
  git:
    image: plugins/git:next

pipeline:
  build-frontend:
    image: node:10.17.0-stretch
    commands:
      - make release-frontend

  build-server:
    group: build
    image: golang:1.16
    commands:
      - make release-server

  build-agent:
    group: build
    image: golang:1.16
    commands:
      - make release-agent

  build-cli:
    group: build
    image: golang:1.16
    commands:
      - make release-cli

  build-docker-server:
    group: bundle
    image: anbraten/kaniko:v1.6.0-debug
    secrets: [docker_username, docker_password]
    environment:
      - IMAGE_TYPE=server
    commands:
      - export WOODPECKER_VERSION=$(make version)
      - .woodpecker/scripts/build-docker-image.sh
    when:
      event: [push, tag]
      branch: master

  build-docker-agent:
    group: bundle
    image: anbraten/kaniko:v1.6.0-debug
    secrets: [docker_username, docker_password]
    environment:
      - IMAGE_TYPE=agent
    commands:
      - export WOODPECKER_VERSION=$(make version)
      - .woodpecker/scripts/build-docker-image.sh
    when:
      event: [push, tag]
      branch: master

  build-docker-cli:
    group: bundle
    image: anbraten/kaniko:v1.6.0-debug
    secrets: [docker_username, docker_password]
    environment:
      - IMAGE_TYPE=cli
    commands:
      - export WOODPECKER_VERSION=$(make version)
      - .woodpecker/scripts/build-docker-image.sh
    when:
      event: [push, tag]
      branch: master

  build-adk-deb-rpm:
    group: bundle
    image: golang:1.16
    commands:
      - go install github.com/goreleaser/nfpm/v2/cmd/nfpm@v1.10.3
      - nfpm package --config ./nfpm/nfpm-server.yml --target ./dist --packager apk
      - nfpm package --config ./nfpm/nfpm-server.yml --target ./dist --packager deb
      - nfpm package --config ./nfpm/nfpm-server.yml --target ./dist --packager rpm
      - nfpm package --config ./nfpm/nfpm-agent.yml --target ./dist --packager apk
      - nfpm package --config ./nfpm/nfpm-agent.yml --target ./dist --packager deb
      - nfpm package --config ./nfpm/nfpm-agent.yml --target ./dist --packager rpm
      - nfpm package --config ./nfpm/nfpm-cli.yml --target ./dist --packager apk
      - nfpm package --config ./nfpm/nfpm-cli.yml --target ./dist --packager deb
      - nfpm package --config ./nfpm/nfpm-cli.yml --target ./dist --packager rpm
    when:
      event: [push, tag]
      branch: master

  changelog:
    image: alpine:3.14.1
    commands:
      - apk add make
      - curl -L https://dl.gitea.io/changelog-tool/master/changelog-master-linux-amd64 > changelog
      - chmod +x ./changelog
      - ./changelog -m=$(make version) generate > CHANGELOG-latest.md
      - ./changelog -m=$(make version) contributors >> CHANGELOG-latest.md
      - echo -e "$(cat CHANGELOG-latest.md)\n$(cat CHANGELOG.md)" > CHANGELOG.md
      # TODO push changed CHANGELOG.md with woodpecker-bot
    when:
      event: tag

  checksums:
    image: golang:1.16
    commands:
      - make release-checksums
    when:
      event: tag

  # TODO: upload build artifacts for pushes to master

  release:
    image: plugins/github-release
    files:
      - dist/*.tar.gz
      - dist/*.apk
      - dist/*.deb
      - dist/*.rpm
      - dist/checksums.txt
    title: ${DRONE_TAG##v}
    note: CHANGELOG-latest.md
    secrets:
      - source: github_token
        target: github_release_api_key
    when:
      event: tag

depends_on:
  - test
