steps:
  release-helper:
    image: woodpeckerci/plugin-ready-release-go:0.6.1
    pull: true
    settings:
      release_branch: ${CI_REPO_DEFAULT_BRANCH}
      forge_type: github
      git_email: woodpecker-bot@obermui.de
      github_token:
        from_secret: GITHUB_TOKEN

when:
  event: push
  branch: ${CI_REPO_DEFAULT_BRANCH}
