variables:
  - &trivy_image aquasec/trivy:latest
  - &trivy_plugin codeberg.org/woodpecker-plugins/trivy:latest

pipeline:
  check backend:
    group: check
    image: *trivy_plugin
    settings:
      skip-dirs: web/,docs/
      server: http://trivy-server:4954

  check docs:
    group: check
    image: *trivy_plugin
    settings:
      skip-dirs: node_modules/,plugins/woodpecker-plugins/node_modules
      server: http://trivy-server:4954
      dir:  docs/
      # TODO currently it is not fixable so just do not block currently
      exit-code: 0

  check web:
    group: check
    image: *trivy_plugin
    settings:
      skip-dirs: node_modules/
      server: http://trivy-server:4954
      dir:  web/

services:
  trivy-server:
    image: *trivy_image
    commands:
      - trivy server
    ports:
      - 4954
