version: 1

when:
  - event: [ pull_request, cron ]
  - event: push
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}
      - release/*

variables:
  - &trivy_image aquasec/trivy:latest
  - &trivy_plugin codeberg.org/woodpecker-plugins/trivy:1.0.1

steps:
  check backend:
    group: check
    image: *trivy_plugin
    settings:
      skip-dirs: web/,docs/

  check docs:
    group: check
    image: *trivy_plugin
    settings:
      skip-dirs: node_modules/,plugins/woodpecker-plugins/node_modules/
      dir:  docs/
    when:
      event: [pull_request, push, cron]
      branch: ${CI_REPO_DEFAULT_BRANCH}

  check web:
    group: check
    image: *trivy_plugin
    settings:
      skip-dirs: node_modules/
      dir:  web/
