when:
  - event: [pull_request, cron]
  - event: push
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}
      - renovate/*

variables:
  - &trivy_plugin docker.io/woodpeckerci/plugin-trivy:1.1.1

steps:
  backend:
    depends_on: []
    image: *trivy_plugin
    settings:
      server: http://server:10000
      skip-dirs: web/,docs/

  docs:
    depends_on: []
    image: *trivy_plugin
    settings:
      server: http://server:10000
      skip-dirs: node_modules/,plugins/woodpecker-plugins/node_modules/
      dir: docs/

  web:
    depends_on: []
    image: *trivy_plugin
    settings:
      server: http://server:10000
      skip-dirs: node_modules/
      dir: web/

services:
  server:
    image: ghcr.io/aquasecurity/trivy:0.57.0
    commands:
      - trivy server --listen 0.0.0.0:10000 --db-repository docker.io/aquasec/trivy-db:2
    ports:
      - 10000
