when:
  - event: [ pull_request, cron ]
    path: &when_path
      - "agent/**"
      - "cli/**"
      - "cmd/**"
      - "server/**"
      - "shared/**"
      - "woodpecker-go/**"
  - event: push
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}
      - release/*
    path: &when_path
      - "agent/**"
      - "cli/**"
      - "cmd/**"
      - "server/**"
      - "shared/**"
      - "woodpecker-go/**"

variables:
  - &trivy_image aquasec/trivy:latest
  - &trivy_plugin codeberg.org/woodpecker-plugins/trivy:latest

steps:
  check backend:
    group: check
    image: *trivy_plugin
    settings:
      skip-dirs: web/,docs/

  check docs:
    group: check
    image: *trivy_plugin
    settings:
      skip-dirs: node_modules/,plugins/woodpecker-plugins/node_modules/
      dir:  docs/
    when:
      event: [pull_request, push, cron]
      branch: ${CI_REPO_DEFAULT_BRANCH}

  check web:
    group: check
    image: *trivy_plugin
    settings:
      skip-dirs: node_modules/
      dir:  web/
