when:
  - event: pull_request

steps:
  - name: lint-editorconfig
    image: docker.io/woodpeckerci/plugin-editorconfig-checker:0.2.0
    depends_on: []
    when:
      - event: pull_request

  - name: spellcheck
    image: docker.io/node:23-alpine
    depends_on: []
    commands:
      - corepack enable
      - pnpx cspell lint --no-progress --gitignore '{**,.*}/{*,.*}'
      - apk add --no-cache -U tree # busybox tree don't understand "-I"
      # cspell:disable-next-line
      - tree --gitignore -I 012_columns_rename_procs_to_steps.go -I versioned_docs -I '*opensource.svg'| pnpx cspell lint --no-progress stdin

  - name: prettier
    image: docker.io/woodpeckerci/plugin-prettier:1.0.0
    depends_on: []
    settings:
      version: 3.3.3
