variables:
  - &golang_image 'docker.io/golang:1.26'
  - &when
    - path: &when_path # related config files
        - '.woodpecker/test.yaml'
        - '.golangci.yaml'
        # go source code
        - '**/*.go'
        - 'go.*'
        # schema changes
        - 'pipeline/schema/**'
        # tools updates
        - Makefile
        - 'codecov.yaml'
      event: pull_request

when:
  - event: pull_request
  - event: push
    branch: ${CI_REPO_DEFAULT_BRANCH}
    path: *when_path

steps:
  lint-license-header:
    image: *golang_image
    commands:
      - pwd
      - ls
      - echo **/*.go
      - make generate-license-header
      - 'DIFF=$(git diff | head)'
      - '[ -n "$DIFF" ] && { echo "license headers not up to date, exec `make generate-license-header` and commit"; exit 1; } || true'
    when: *when
