variables:
  - &golang_image 'docker.io/golang:1.26'
  - &when
    - path: &when_path # related config files
        - '.woodpecker/test.yaml'
        - '.golangci.yaml'
        # go source code
        - '**/*.go'
        - 'go.*'
        # schema changes
        - 'pipeline/schema/**'
        # tools updates
        - Makefile
        - 'codecov.yaml'
      event: pull_request

when:
  - event: pull_request
  - event: push
    branch: ${CI_REPO_DEFAULT_BRANCH}
    path: *when_path

steps:
  lint-license-header:
    image: *golang_image
    commands:
      - make install-addlicense # cspell:words addlicense
      - pwd
      - 'addlicense -check -ignore "vendor/**" -ignore cmd/server/openapi/docs.go $(pwd)/**/*.go'
    when: *when
