clone:
  git:
    image: plugins/git:next

pipeline:
  deps:
    image: node:14-alpine
    commands:
      - cd web/
      - curl -f https://get.pnpm.io/v6.js | node - add --global pnpm@6
      - pnpm config set store-dir .pnpm-store
      - pnpm install
    when:
      path: "web/*"

  lint:
    group: test
    image: node:14-alpine
    commands:
      - cd web/
      - pnpm lint
    when:
      path: "web/*"

  formatcheck:
    group: test
    image: node:14-alpine
    commands:
      - cd web/
      - pnpm formatcheck
    when:
      path: "web/*"

  typecheck:
    group: test
    image: node:14-alpine
    commands:
      - cd web/
      - pnpm typecheck
    when:
      path: "web/*"

  build:
    image: node:14-alpine
    commands:
      - pnpm build
    when:
      path: "web/*"
