variables:
  - &node_image 'node:16-alpine'
  - &when_path
      # related config files
      - ".woodpecker/web.yml"
      # web source code
      - "web/**"

when:
  - event: push
    branch: ["${CI_REPO_DEFAULT_BRANCH}", "release/*" ]
    path: *when_path
  - event: tag
  - event: pull_request
    path: *when_path

pipeline:
  deps:
    image: *node_image
    commands:
      - cd web/
      - corepack enable
      - pnpm install --frozen-lockfile

  lint:
    group: test
    image: *node_image
    commands:
      - cd web/
      - corepack enable
      - pnpm lint

  formatcheck:
    group: test
    image: *node_image
    commands:
      - cd web/
      - corepack enable
      - pnpm formatcheck

  typecheck:
    group: test
    image: *node_image
    commands:
      - cd web/
      - corepack enable
      - pnpm typecheck

  securitycheck:
    group: test
    image: aquasec/trivy:latest
    commands:
      - trivy fs --exit-code 0 --skip-dirs node_modules/ --severity UNKNOWN,LOW web/
      - trivy fs --exit-code 1 --skip-dirs node_modules/ --severity MEDIUM,HIGH,CRITICAL web/

  test:
    group: test
    image: *node_image
    commands:
      - cd web/
      - corepack enable
      - pnpm test
