when:
  - event: [pull_request, tag]
  - event: push
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}
      - release/*

variables:
  - &node_image 'node:20-alpine'
  - &when
    path:
      # related config files
      - ".woodpecker/web.yml"
      # web source code
      - "web/**"
      # api source code
      - "server/api/**"
    event: [pull_request, tag, deployment]

steps:
  - name: deps
    image: *node_image
    directory: web/
    commands:
      - corepack enable
      - pnpm install --frozen-lockfile
    when: *when

  - name: lint
    group: test
    image: *node_image
    directory: web/
    commands:
      - corepack enable
      - pnpm lint
    when: *when

  - name: formatcheck
    group: test
    image: *node_image
    directory: web/
    commands:
      - corepack enable
      - pnpm format:check
    when: *when

  - name: typecheck
    group: test
    image: *node_image
    directory: web/
    commands:
      - corepack enable
      - pnpm typecheck
    when: *when

  - name: test
    group: test
    image: *node_image
    directory: web/
    commands:
      - corepack enable
      - pnpm test
    when: *when
