clone:
  git:
    image: plugins/git:next

pipeline:
  deps:
    image: node:14-alpine
    commands:
      - cd web/
      - curl -f https://get.pnpm.io/v6.js | node - add --global pnpm@6
      - pnpm config set store-dir .pnpm-store
      - pnpm install

  lint:
    group: test
    image: node:14-alpine
    commands:
      - cd web/
      - pnpm lint

  formatcheck:
    group: test
    image: node:14-alpine
    commands:
      - cd web/
      - pnpm formatcheck

  typecheck:
    group: test
    image: node:14-alpine
    commands:
      - cd web/
      - pnpm typecheck

  build:
    image: node:14-alpine
    commands:
      - pnpm build
