// Code generated by go-swagger; DO NOT EDIT.

package organization_secrets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"go.woodpecker-ci.org/woodpecker/v2/woodpecker-go/models"
)

// GetOrgsOrgIDSecretsReader is a Reader for the GetOrgsOrgIDSecrets structure.
type GetOrgsOrgIDSecretsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOrgsOrgIDSecretsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetOrgsOrgIDSecretsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /orgs/{org_id}/secrets] GetOrgsOrgIDSecrets", response, response.Code())
	}
}

// NewGetOrgsOrgIDSecretsOK creates a GetOrgsOrgIDSecretsOK with default headers values
func NewGetOrgsOrgIDSecretsOK() *GetOrgsOrgIDSecretsOK {
	return &GetOrgsOrgIDSecretsOK{}
}

/*
GetOrgsOrgIDSecretsOK describes a response with status code 200, with default header values.

OK
*/
type GetOrgsOrgIDSecretsOK struct {
	Payload []*models.Secret
}

// IsSuccess returns true when this get orgs org Id secrets o k response has a 2xx status code
func (o *GetOrgsOrgIDSecretsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get orgs org Id secrets o k response has a 3xx status code
func (o *GetOrgsOrgIDSecretsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get orgs org Id secrets o k response has a 4xx status code
func (o *GetOrgsOrgIDSecretsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get orgs org Id secrets o k response has a 5xx status code
func (o *GetOrgsOrgIDSecretsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get orgs org Id secrets o k response a status code equal to that given
func (o *GetOrgsOrgIDSecretsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get orgs org Id secrets o k response
func (o *GetOrgsOrgIDSecretsOK) Code() int {
	return 200
}

func (o *GetOrgsOrgIDSecretsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /orgs/{org_id}/secrets][%d] getOrgsOrgIdSecretsOK %s", 200, payload)
}

func (o *GetOrgsOrgIDSecretsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /orgs/{org_id}/secrets][%d] getOrgsOrgIdSecretsOK %s", 200, payload)
}

func (o *GetOrgsOrgIDSecretsOK) GetPayload() []*models.Secret {
	return o.Payload
}

func (o *GetOrgsOrgIDSecretsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
