// Code generated by go-swagger; DO NOT EDIT.

package organization_secrets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetOrgsOrgIDSecretsParams creates a new GetOrgsOrgIDSecretsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetOrgsOrgIDSecretsParams() *GetOrgsOrgIDSecretsParams {
	return &GetOrgsOrgIDSecretsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetOrgsOrgIDSecretsParamsWithTimeout creates a new GetOrgsOrgIDSecretsParams object
// with the ability to set a timeout on a request.
func NewGetOrgsOrgIDSecretsParamsWithTimeout(timeout time.Duration) *GetOrgsOrgIDSecretsParams {
	return &GetOrgsOrgIDSecretsParams{
		timeout: timeout,
	}
}

// NewGetOrgsOrgIDSecretsParamsWithContext creates a new GetOrgsOrgIDSecretsParams object
// with the ability to set a context for a request.
func NewGetOrgsOrgIDSecretsParamsWithContext(ctx context.Context) *GetOrgsOrgIDSecretsParams {
	return &GetOrgsOrgIDSecretsParams{
		Context: ctx,
	}
}

// NewGetOrgsOrgIDSecretsParamsWithHTTPClient creates a new GetOrgsOrgIDSecretsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetOrgsOrgIDSecretsParamsWithHTTPClient(client *http.Client) *GetOrgsOrgIDSecretsParams {
	return &GetOrgsOrgIDSecretsParams{
		HTTPClient: client,
	}
}

/*
GetOrgsOrgIDSecretsParams contains all the parameters to send to the API endpoint

	for the get orgs org ID secrets operation.

	Typically these are written to a http.Request.
*/
type GetOrgsOrgIDSecretsParams struct {

	/* Authorization.

	   Insert your personal access token

	   Default: "Bearer \u003cpersonal access token\u003e"
	*/
	Authorization string

	/* OrgID.

	   the org's id
	*/
	OrgID string

	/* Page.

	   for response pagination, page offset number

	   Default: 1
	*/
	Page *int64

	/* PerPage.

	   for response pagination, max items per page

	   Default: 50
	*/
	PerPage *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get orgs org ID secrets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOrgsOrgIDSecretsParams) WithDefaults() *GetOrgsOrgIDSecretsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get orgs org ID secrets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOrgsOrgIDSecretsParams) SetDefaults() {
	var (
		authorizationDefault = string("Bearer <personal access token>")

		pageDefault = int64(1)

		perPageDefault = int64(50)
	)

	val := GetOrgsOrgIDSecretsParams{
		Authorization: authorizationDefault,
		Page:          &pageDefault,
		PerPage:       &perPageDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get orgs org ID secrets params
func (o *GetOrgsOrgIDSecretsParams) WithTimeout(timeout time.Duration) *GetOrgsOrgIDSecretsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get orgs org ID secrets params
func (o *GetOrgsOrgIDSecretsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get orgs org ID secrets params
func (o *GetOrgsOrgIDSecretsParams) WithContext(ctx context.Context) *GetOrgsOrgIDSecretsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get orgs org ID secrets params
func (o *GetOrgsOrgIDSecretsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get orgs org ID secrets params
func (o *GetOrgsOrgIDSecretsParams) WithHTTPClient(client *http.Client) *GetOrgsOrgIDSecretsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get orgs org ID secrets params
func (o *GetOrgsOrgIDSecretsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the get orgs org ID secrets params
func (o *GetOrgsOrgIDSecretsParams) WithAuthorization(authorization string) *GetOrgsOrgIDSecretsParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the get orgs org ID secrets params
func (o *GetOrgsOrgIDSecretsParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithOrgID adds the orgID to the get orgs org ID secrets params
func (o *GetOrgsOrgIDSecretsParams) WithOrgID(orgID string) *GetOrgsOrgIDSecretsParams {
	o.SetOrgID(orgID)
	return o
}

// SetOrgID adds the orgId to the get orgs org ID secrets params
func (o *GetOrgsOrgIDSecretsParams) SetOrgID(orgID string) {
	o.OrgID = orgID
}

// WithPage adds the page to the get orgs org ID secrets params
func (o *GetOrgsOrgIDSecretsParams) WithPage(page *int64) *GetOrgsOrgIDSecretsParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get orgs org ID secrets params
func (o *GetOrgsOrgIDSecretsParams) SetPage(page *int64) {
	o.Page = page
}

// WithPerPage adds the perPage to the get orgs org ID secrets params
func (o *GetOrgsOrgIDSecretsParams) WithPerPage(perPage *int64) *GetOrgsOrgIDSecretsParams {
	o.SetPerPage(perPage)
	return o
}

// SetPerPage adds the perPage to the get orgs org ID secrets params
func (o *GetOrgsOrgIDSecretsParams) SetPerPage(perPage *int64) {
	o.PerPage = perPage
}

// WriteToRequest writes these params to a swagger request
func (o *GetOrgsOrgIDSecretsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// path param org_id
	if err := r.SetPathParam("org_id", o.OrgID); err != nil {
		return err
	}

	if o.Page != nil {

		// query param page
		var qrPage int64

		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt64(qrPage)
		if qPage != "" {

			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}
	}

	if o.PerPage != nil {

		// query param perPage
		var qrPerPage int64

		if o.PerPage != nil {
			qrPerPage = *o.PerPage
		}
		qPerPage := swag.FormatInt64(qrPerPage)
		if qPerPage != "" {

			if err := r.SetQueryParam("perPage", qPerPage); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
