steps:
  - name: image
    image: golang
    commands:
      - go test

  - name: image-pull
    image: golang
    pull: true
    commands:
      - go test

  - name: single-command
    image: golang
    commands: go test

  - name: commands
    image: golang
    commands:
      - go get
      - go test

  - name: environment
    image: golang
    environment:
      CGO: 0
      GOOS: linux
      GOARCH: amd64
    commands:
      - go test

  - name: environment-array
    image: golang
    environment:
      - CGO=0
      - GOOS=linux
      - GOARCH=amd64
    commands:
      - go test

  - name: secrets
    image: docker
    commands:
      - echo $DOCKER_USERNAME
      - echo $DOCKER_PASSWORD
    secrets:
      - docker_username
      - source: docker_prod_password
        target: docker_password

  - name: group
    group: test
    image: golang
    commands:
      - go test

  - name: detached
    image: redis
    detach: true

  - name: volume
    image: docker
    commands:
      - docker build --rm -t octocat/hello-world .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
