steps:
  - name: when-branch
    image: alpine
    commands:
      - echo "test"
    when:
      branch: main

  - name: when-branch-array
    image: alpine
    commands:
      - echo "test"
    when:
      branch: [main, deploy]

  - name: when-event
    image: alpine
    commands:
      - echo "test"
    when:
      event: push

  - name: when-event-array
    image: alpine
    commands:
      - echo "test"
    when:
      event: [push, pull_request, tag, deployment]

  - name: when-ref
    image: alpine
    commands:
      - echo "test"
    when:
      ref: 'refs/tags/v**'

  - name: when-status
    image: alpine
    commands:
      - echo "test"
    when:
      status: [success, failure]

  - name: when-platform
    image: alpine
    commands:
      - echo "test"
    when:
      platform: linux/amd64

  - name: when-platform-array
    image: alpine
    commands:
      - echo "test"
    when:
      platform: [linux/*, windows/amd64]

  - name: when-environment
    image: alpine
    commands:
      - echo "test"
    when:
      environment: production
      event: deployment

  - name: when-matrix
    image: alpine
    commands:
      - echo "test"
    when:
      matrix:
        GO_VERSION: 1.5
        REDIS_VERSION: 2.8

  - name: when-instance
    image: alpine
    commands:
      - echo "test"
    when:
      instance: stage.woodpecker.company.com

  - name: when-path
    image: alpine
    commands:
      - echo "test"
    when:
      path: 'folder/**'

  - name: when-path-array
    image: alpine
    commands:
      - echo "test"
    when:
      path:
        - 'folder/**'
        - '**/*.c'

  - name: when-path-include-exclude
    image: alpine
    commands:
      - echo "test"
    when:
      path:
        include: ['.woodpecker/*.yml', '*.ini']
        exclude: ['*.md', 'docs/**']
        ignore_message: '[ALL]'

  - name: when-repo
    image: alpine
    commands:
      - echo "test"
    when:
      repo: test/test

  - name: when-multi
    image: alpine
    commands:
      - echo "test"
    when:
      - event: pull_request
        repo: test/test
      - event: push
        branch: main

  - name: when-cron
    image: alpine
    commands:
      - echo "test"
    when:
      cron: 'update locales'
      event: cron

  - name: when-cron-list
    image: alpine
    commands: echo "test"
    when:
      - event: cron
        cron:
          include:
            - test
            - hello
          exclude: hi

  - name: when-evaluate
    image: alpine
    commands: echo "test"
    when:
      - event: push
        evaluate: 'CI_PIPELINE_EVENT == "push" && CI_REPO == "owner/repo"'
