FROM alpine:3.14.1
EXPOSE 8000 9000 80 443

RUN apk add -U --no-cache ca-certificates

ENV GODEBUG=netdns=go
ENV XDG_CACHE_HOME=/var/lib/drone
ENV WOODPECKER_DATABASE_DRIVER=sqlite3
ENV WOODPECKER_DATABASE_DATASOURCE=/var/lib/drone/drone.sqlite

ADD ./woodpecker-server /bin/

ENTRYPOINT ["/bin/woodpecker-server"]
