FROM alpine:3.14.1
EXPOSE 8000 9000 80 443

RUN apk add -U --no-cache ca-certificates

ENV DATABASE_DRIVER=sqlite3
ENV DATABASE_CONFIG=/var/lib/drone/drone.sqlite
ENV GODEBUG=netdns=go
ENV XDG_CACHE_HOME /var/lib/drone

ADD ./woodpecker-server /bin/

ENTRYPOINT ["/bin/woodpecker-server"]
